-- Drop policies IF THEY EXIST to avoid errors on a clean slate
DROP POLICY IF EXISTS "Users can manage their own profiles." ON "public"."profiles";
DROP POLICY IF EXISTS "Users can view all profiles." ON "public"."profiles";
DROP POLICY IF EXISTS "Users can manage their own addresses." ON "public"."addresses";

-- Drop trigger and function IF THEY EXIST
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Drop tables using IF EXISTS and CASCADE to handle dependencies
DROP TABLE IF EXISTS "public"."reviews" CASCADE;
DROP TABLE IF EXISTS "public"."wishlist_items" CASCADE;
DROP TABLE IF EXISTS "public"."wishlists" CASCADE;
DROP TABLE IF EXISTS "public"."order_items" CASCADE;
DROP TABLE IF EXISTS "public"."orders" CASCADE;
DROP TABLE IF EXISTS "public"."cards" CASCADE;
DROP TABLE IF EXISTS "public"."addresses" CASCADE;
DROP TABLE IF EXISTS "public"."questions" CASCADE;
DROP TABLE IF EXISTS "public"."refunds" CASCADE;
DROP TABLE IF EXISTS "public"."notifications" CASCADE;
DROP TABLE IF EXISTS "public"."products" CASCADE;
DROP TABLE IF EXISTS "public"."categories" CASCADE;
DROP TABLE IF EXISTS "public"."profiles" CASCADE;
DROP TABLE IF EXISTS "public"."cart_items" CASCADE;


-- 1. PROFILES
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NULL,
  avatar_url text NULL,
  bio text NULL,
  contact_number text NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own profiles." ON "public"."profiles"
  FOR ALL
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view all profiles." ON "public"."profiles"
  FOR SELECT
  USING (true);

-- 2. FUNCTION AND TRIGGER TO CREATE A PROFILE FOR A NEW USER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 3. ADDRESSES
CREATE TABLE public.addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  address_type TEXT,
  title TEXT,
  country TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  street_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own addresses." ON "public"."addresses"
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 4. CATEGORIES
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    parent_id BIGINT REFERENCES public.categories(id)
);


-- 5. PRODUCTS
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    original_price NUMERIC(10, 2),
    stock INT NOT NULL DEFAULT 0,
    sku TEXT UNIQUE,
    image_url TEXT,
    category_id BIGINT REFERENCES public.categories(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 6. ORDERS
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    shipping_address_id BIGINT REFERENCES public.addresses(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 7. ORDER ITEMS
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    quantity INT NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);


-- 8. CARDS (for storing payment method references)
CREATE TABLE public.cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_type TEXT,
    last4 TEXT,
    expiry_date TEXT,
    payment_method_id TEXT NOT NULL UNIQUE, -- e.g., Stripe PaymentMethod ID
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 9. WISHLISTS
CREATE TABLE public.wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 10. WISHLIST ITEMS
CREATE TABLE public.wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT NOT NULL REFERENCES public.wishlists(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 11. REVIEWS
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 12. QUESTIONS
CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    question_text TEXT NOT NULL,
    answer_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 13. REFUNDS
CREATE TABLE public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id),
    user_id UUID NOT NULL REFERENCES auth.users(id),
    amount NUMERIC(10, 2) NOT NULL,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 14. NOTIFICATIONS
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. CART ITEMS (for persistent cart)
CREATE TABLE public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    quantity INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, product_id)
);
