-- This script is designed to be idempotent (re-runnable).
-- It will drop existing objects before recreating them to ensure a clean state.

-- Drop dependent objects first in reverse order of creation.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Drop all known policies on storage.objects to prevent "already exists" errors.
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own avatar." ON storage.objects;

-- Drop all known policies on tables before dropping the tables themselves.
DROP POLICY IF EXISTS "Users can manage their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Profiles are publicly visible." ON public.profiles;
DROP POLICY IF EXISTS "Users can manage their own addresses." ON public.addresses;
DROP POLICY IF EXISTS "Users can view their own orders." ON public.orders;
DROP POLICY IF EXISTS "Users can manage their own reviews." ON public.reviews;
DROP POLICY IF EXISTS "Users can manage their own questions." ON public.questions;
DROP POLICY IF EXISTS "Users can manage their own wishlists." ON public.wishlists;
DROP POLICY IF EXISTS "Users can manage their own wishlist items." ON public.wishlist_items;

-- Drop tables using CASCADE to handle any remaining dependencies.
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.wishlist_items CASCADE;
DROP TABLE IF EXISTS public.wishlists CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.carts CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.addresses CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 1. Profiles Table
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  avatar_url text,
  bio text,
  contact_number text,
  email text
);
COMMENT ON TABLE public.profiles IS 'Public profile information for each user.';

-- 2. Addresses Table
CREATE TABLE public.addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  address_type text,
  title text,
  country text,
  city text,
  state text,
  zip text,
  street_address text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.addresses IS 'Stores user shipping and billing addresses.';

-- 3. Categories Table
CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  parent_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.categories IS 'Product categories and sub-categories.';

-- 4. Products Table
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  price numeric(10, 2) NOT NULL,
  original_price numeric(10, 2),
  stock integer DEFAULT 0,
  sku text UNIQUE,
  image_url text,
  category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.products IS 'Stores all product information.';

-- 5. Orders and Order Items
CREATE TABLE public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  total numeric(10, 2) NOT NULL,
  status text NOT NULL,
  shipping_address_id bigint REFERENCES public.addresses(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.orders IS 'Represents a customer order.';

CREATE TABLE public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity integer NOT NULL,
  price_at_purchase numeric(10, 2) NOT NULL
);
COMMENT ON TABLE public.order_items IS 'Individual items within an order.';

-- 6. Reviews Table
CREATE TABLE public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  text text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.reviews IS 'User reviews for products.';

-- 7. Questions Table
CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  answer_text text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.questions IS 'User questions about products and their answers.';

-- 8. Wishlists Table
CREATE TABLE public.wishlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name text DEFAULT 'My Wishlist'
);
COMMENT ON TABLE public.wishlists IS 'User wishlists.';

CREATE TABLE public.wishlist_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wishlist_id bigint NOT NULL REFERENCES public.wishlists(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(wishlist_id, product_id)
);
COMMENT ON TABLE public.wishlist_items IS 'Items within a wishlist.';


-- Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Profiles are publicly visible."
ON public.profiles FOR SELECT
USING (true);

CREATE POLICY "Users can manage their own profile."
ON public.profiles FOR ALL
USING (auth.uid() = id);

-- Policies for Addresses
CREATE POLICY "Users can manage their own addresses."
ON public.addresses FOR ALL
USING (auth.uid() = user_id);

-- Policies for Orders
CREATE POLICY "Users can view their own orders."
ON public.orders FOR SELECT
USING (auth.uid() = user_id);

-- Policies for Reviews, Questions, Wishlists
CREATE POLICY "Users can manage their own reviews." ON public.reviews FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own questions." ON public.questions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own wishlists." ON public.wishlists FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own wishlist items." ON public.wishlist_items FOR ALL USING (wishlist_id IN (SELECT id FROM wishlists WHERE user_id = auth.uid()));


-- Function to create a public profile for a new user.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$;

-- Trigger to call the function when a new user signs up.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Set up Storage
-- Create a bucket for 'avatars' with public access.
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for Avatars bucket
CREATE POLICY "Avatar images are publicly accessible."
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

CREATE POLICY "Users can upload their own avatar."
ON storage.objects FOR INSERT
WITH CHECK (auth.uid() = owner AND bucket_id = 'avatars');

CREATE POLICY "Users can update their own avatar."
ON storage.objects FOR UPDATE
USING (auth.uid() = owner)
WITH CHECK (bucket_id = 'avatars');
