-- This script updates the database schema for the order management system.
-- It renames the 'total' column to 'total_amount' in the 'orders' table to fix a naming inconsistency.
-- It also recreates the 'create_order' function to use this new column name.
-- This approach preserves existing order data.

-- Note: Run this script in your Supabase SQL editor.

DO $$
BEGIN
    -- Check if the 'total' column exists and 'total_amount' does not, then rename it.
    IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='orders' AND column_name='total')
    AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='orders' AND column_name='total_amount') THEN
        ALTER TABLE public.orders RENAME COLUMN total TO total_amount;
    END IF;
END $$;


-- Recreate the function to ensure it uses the correct column name 'total_amount'.
-- This also updates the p_shipping_details type to jsonb for consistency.
CREATE OR REPLACE FUNCTION create_order(
  p_total_amount numeric,
  p_shipping_details jsonb,
  p_items json,
  p_user_id uuid default auth.uid()
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_order_id int;
  new_order_number text;
  item record;
BEGIN
  -- Generate a unique order number if the sequence exists
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'order_number_seq') THEN
    new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || nextval('order_number_seq');
  ELSE
    new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || (RANDOM() * 10000)::INT;
  END IF;

  -- Insert the new order and get its ID
  INSERT INTO public.orders (user_id, order_number, total_amount, status, shipping_details)
  VALUES (p_user_id, new_order_number, p_total_amount, 'Pending', p_shipping_details)
  RETURNING id INTO new_order_id;

  -- Loop through the items and insert them into order_items
  FOR item IN SELECT * FROM json_to_recordset(p_items) AS x(product_id int, quantity int, price numeric)
  LOOP
    INSERT INTO public.order_items (order_id, product_id, quantity, price)
    VALUES (new_order_id, item.product_id, item.quantity, item.price);
  END LOOP;

  RETURN new_order_number;
END;
$$;


-- These commands are for reference and to ensure the full schema is present.
-- They are safe to run multiple times.

CREATE SEQUENCE IF NOT EXISTS order_number_seq;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        CREATE TYPE public.order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.orders (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    order_number text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    total_amount numeric(10, 2) not null,
    status public.order_status not null default 'Pending',
    shipping_details jsonb
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    product_id bigint references public.products(id) on delete set null,
    quantity int not null,
    price numeric(10, 2) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);