-- Drop existing types and functions to ensure a clean slate.
-- CASCADE will remove any dependent objects, like functions using the type.
DROP FUNCTION IF EXISTS public.create_order(numeric, jsonb, json, uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, public.order_item_input[]) CASCADE;
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, jsonb) CASCADE;
DROP TYPE IF EXISTS public.order_item_input CASCADE;


-- Recreate tables if they don't exist, with all correct columns.
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'Pending'::text NOT NULL,
    total_amount numeric NOT NULL,
    shipping_details jsonb,
    order_number text UNIQUE
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id int REFERENCES public.products(id),
    quantity int NOT NULL,
    price_at_purchase numeric NOT NULL
);

-- Recreate the create_order function with the robust jsonb input type.
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb
)
RETURNS text
LANGUAGE plpgsql
-- SECURITY DEFINER allows this function to bypass RLS for inserts.
SECURITY DEFINER
AS $$
DECLARE
    new_order_id int;
    new_order_number text;
    item jsonb;
BEGIN
    -- Generate a unique order number.
    new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || substr(md5(random()::text), 1, 6);

    -- Insert into orders table.
    INSERT INTO public.orders (user_id, total_amount, status, shipping_details, order_number)
    VALUES (p_user_id, p_total_amount, 'Pending', p_shipping_details, new_order_number)
    RETURNING id INTO new_order_id;

    -- Insert into order_items table by looping through the jsonb array.
    FOR item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (
            new_order_id,
            (item->>'product_id')::int,
            (item->>'quantity')::int,
            (item->>'price_at_purchase')::numeric
        );
    END LOOP;

    RETURN new_order_number;
END;
$$;

-- Enable Row Level Security (RLS) on the tables.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Drop old policies if they exist, to be safe.
DROP POLICY IF EXISTS "Users can view their own orders." ON public.orders;
DROP POLICY IF EXISTS "Users can view their own order items." ON public.order_items;

-- Create policies to allow users to view their own data.
CREATE POLICY "Users can view their own orders."
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own order items."
ON public.order_items
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.orders
    WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid()
  )
);
