-- Drop all potentially conflicting old function definitions and their dependent types
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, public.order_item_input[]) CASCADE;
DROP FUNCTION IF EXISTS public.create_order(numeric, jsonb, json, uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, jsonb) CASCADE;
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, json) CASCADE;
DROP TYPE IF EXISTS public.order_item_input CASCADE;


-- Recreate the orders table with the correct column name if it doesn't exist
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NULL,
    total_amount numeric NULL,
    status text NULL DEFAULT 'Pending'::text,
    shipping_details jsonb NULL,
    order_number text NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_number_key UNIQUE (order_number),
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE SET NULL
);

-- Ensure RLS is enabled and policies are in place
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users to read their own orders" ON public.orders;
CREATE POLICY "Allow authenticated users to read their own orders" ON public.orders FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Allow authenticated users to insert their own orders" ON public.orders;
CREATE POLICY "Allow authenticated users to insert their own orders" ON public.orders FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);


-- Recreate order_items table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    order_id bigint NULL,
    product_id bigint NULL,
    quantity integer NULL,
    price numeric NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id) ON DELETE CASCADE,
    CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE SET NULL
);

-- Ensure RLS is enabled and policies are in place for order_items
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow users to read order_items for their own orders" ON public.order_items;
CREATE POLICY "Allow users to read order_items for their own orders" ON public.order_items FOR SELECT TO authenticated USING (
  (auth.uid() = ( SELECT user_id FROM orders WHERE id = order_items.order_id ))
);


-- Create the single, correct create_order function
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_order_id bigint;
  new_order_number text;
  item_data jsonb;
BEGIN
  -- Generate a unique order number using the sequence
  new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || nextval('orders_id_seq');

  -- Insert the new order
  INSERT INTO public.orders (user_id, total_amount, shipping_details, order_number, status)
  VALUES (p_user_id, p_total_amount, p_shipping_details, new_order_number, 'Pending')
  RETURNING id INTO new_order_id;

  -- Loop through the items JSONB array and insert each item
  FOR item_data IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.order_items (order_id, product_id, quantity, price)
    VALUES (
      new_order_id,
      (item_data->>'product_id')::bigint,
      (item_data->>'quantity')::integer,
      (item_data->>'price')::numeric
    );
  END LOOP;

  -- Return the generated order number
  RETURN new_order_number;
END;
$$;

-- Grant execution rights to the function
GRANT EXECUTE ON FUNCTION public.create_order(uuid, numeric, jsonb, jsonb) TO authenticated;
