-- Drop existing tables in reverse order of dependency
DROP TABLE IF EXISTS public.product_tags CASCADE;
DROP TABLE IF EXISTS public.product_categories CASCADE;
DROP TABLE IF EXISTS public.home_page_sections CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;


-- Categories Table
CREATE TABLE public.categories (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text,
    parent_id bigint REFERENCES public.categories(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tags Table
CREATE TABLE public.tags (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Products Table
CREATE TABLE public.products (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text,
    unit text, -- e.g., 1kg, 1pc
    price numeric NOT NULL,
    original_price numeric,
    stock integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'draft', -- e.g., draft, active, archived
    featured_image_url text,
    gallery_urls text[],
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    category_id bigint REFERENCES public.categories(id)
);

-- Product Categories Junction Table (Many-to-Many)
CREATE TABLE public.product_categories (
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, category_id)
);


-- Product Tags Junction Table (Many-to-Many)
CREATE TABLE public.product_tags (
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);

-- Home Page Sections Table
CREATE TABLE public.home_page_sections (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint REFERENCES public.categories(id) ON DELETE CASCADE,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- Enable RLS for all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_page_sections ENABLE ROW LEVEL SECURITY;


-- POLICIES

-- Policies for categories
CREATE POLICY "Public categories are viewable by everyone." ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admin users can manage categories." ON public.categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Policies for tags
CREATE POLICY "Public tags are viewable by everyone." ON public.tags FOR SELECT USING (true);
CREATE POLICY "Admin users can manage tags." ON public.tags FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Policies for products
CREATE POLICY "Public products are viewable by everyone." ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin users can manage products." ON public.products FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Policies for product_categories
CREATE POLICY "Public product_categories are viewable by everyone." ON public.product_categories FOR SELECT USING (true);
CREATE POLICY "Admin users can manage product_categories." ON public.product_categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Policies for product_tags
CREATE POLICY "Public product_tags are viewable by everyone." ON public.product_tags FOR SELECT USING (true);
CREATE POLICY "Admin users can manage product_tags." ON public.product_tags FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Policies for home_page_sections
CREATE POLICY "Public home_page_sections are viewable by everyone." ON public.home_page_sections FOR SELECT USING (true);
CREATE POLICY "Admin users can manage home page sections." ON public.home_page_sections FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
