-- Enable HTTP extension
CREATE EXTENSION IF NOT EXISTS http WITH SCHEMA extensions;

-- Enable vector extension
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- Function to update modified_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop existing tables in reverse order of dependency
DROP TABLE IF EXISTS public.product_tags CASCADE;
DROP TABLE IF EXISTS public.product_categories CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;


-- Create categories table with parent-child relationship
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT REFERENCES public.categories,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.categories IS 'Stores product categories and sub-categories.';

-- Create tags table
CREATE TABLE public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.tags IS 'Stores product tags.';


-- Create products table (without category_id)
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  unit TEXT,
  price REAL NOT NULL,
  original_price REAL,
  stock INTEGER DEFAULT 0,
  status TEXT DEFAULT 'draft',
  featured_image_url TEXT,
  gallery_urls TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.products IS 'Stores product information.';


-- Create product_categories join table
CREATE TABLE public.product_categories (
  product_id BIGINT NOT NULL REFERENCES public.products ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories ON DELETE CASCADE,
  PRIMARY KEY (product_id, category_id)
);
COMMENT ON TABLE public.product_categories IS 'Links products to their categories.';

-- Create product_tags join table
CREATE TABLE public.product_tags (
  product_id BIGINT NOT NULL REFERENCES public.products ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES public.tags ON DELETE CASCADE,
  PRIMARY KEY (product_id, tag_id)
);
COMMENT ON TABLE public.product_tags IS 'Links products to their tags.';


-- Create triggers for updated_at
CREATE TRIGGER handle_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER handle_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER handle_tags_updated_at BEFORE UPDATE ON public.tags FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- Policies for categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are viewable by everyone." ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admins can insert categories." ON public.categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update categories." ON public.categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete categories." ON public.categories FOR DELETE USING (auth.role() = 'authenticated');

-- Policies for tags
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tags are viewable by everyone." ON public.tags FOR SELECT USING (true);
CREATE POLICY "Admins can insert tags." ON public.tags FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update tags." ON public.tags FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete tags." ON public.tags FOR DELETE USING (auth.role() = 'authenticated');

-- Policies for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products are viewable by everyone." ON public.products FOR SELECT USING (true);
CREATE POLICY "Admins can insert products." ON public.products FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update products." ON public.products FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete products." ON public.products FOR DELETE USING (auth.role() = 'authenticated');

-- Policies for product_categories
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Product categories are viewable by everyone." ON public.product_categories FOR SELECT USING (true);
CREATE POLICY "Admins can manage product categories." ON public.product_categories FOR ALL USING (auth.role() = 'authenticated');

-- Policies for product_tags
ALTER TABLE public.product_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Product tags are viewable by everyone." ON public.product_tags FOR SELECT USING (true);
CREATE POLICY "Admins can manage product tags." ON public.product_tags FOR ALL USING (auth.role() = 'authenticated');


-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
