-- Drop existing tables with CASCADE to handle dependencies
DROP TABLE IF EXISTS public.product_tags CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;

-- Create the categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON COLUMN public.categories.parent_id IS 'Self-referencing foreign key for sub-categories';

-- Create the tags table
CREATE TABLE public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create the products table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    unit TEXT,
    price REAL NOT NULL DEFAULT 0,
    original_price REAL,
    stock INT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    featured_image_url TEXT,
    gallery_urls TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create the product_tags join table
CREATE TABLE public.product_tags (
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);


-- Enable Row Level Security (RLS) for all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_tags ENABLE ROW LEVEL SECURITY;


-- POLICIES for 'categories' table
DROP POLICY IF EXISTS "Allow all access to authenticated users for categories" ON public.categories;
CREATE POLICY "Allow all access to authenticated users for categories"
ON public.categories
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Categories are viewable by everyone" ON public.categories;
CREATE POLICY "Categories are viewable by everyone"
ON public.categories
FOR SELECT
TO public
USING (true);


-- POLICIES for 'tags' table
DROP POLICY IF EXISTS "Allow all access to authenticated users for tags" ON public.tags;
CREATE POLICY "Allow all access to authenticated users for tags"
ON public.tags
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Tags are viewable by everyone" ON public.tags;
CREATE POLICY "Tags are viewable by everyone"
ON public.tags
FOR SELECT
TO public
USING (true);


-- POLICIES for 'products' table
DROP POLICY IF EXISTS "Allow all access to authenticated users for products" ON public.products;
CREATE POLICY "Allow all access to authenticated users for products"
ON public.products
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Products are viewable by everyone" ON public.products;
CREATE POLICY "Products are viewable by everyone"
ON public.products
FOR SELECT
TO public
USING (true);


-- POLICIES for 'product_tags' table
DROP POLICY IF EXISTS "Allow all access to authenticated users for product_tags" ON public.product_tags;
CREATE POLICY "Allow all access to authenticated users for product_tags"
ON public.product_tags
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Product tags are viewable by everyone" ON public.product_tags;
CREATE POLICY "Product tags are viewable by everyone"
ON public.product_tags
FOR SELECT
TO public
USING (true);


-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
