-- Create a table for public profiles
create table if not exists profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  avatar_url text,
  bio text,
  contact_number text,
  updated_at timestamp with time zone,

  primary key (id)
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for addresses
create table if not exists addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  address_type text not null,
  title text not null,
  country text not null,
  city text not null,
  state text not null,
  zip text not null,
  street_address text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for addresses
alter table addresses enable row level security;
create policy "Users can manage their own addresses." on addresses
  for all using (auth.uid() = user_id);

-- Create a table for saved cards
create table if not exists cards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  card_type text not null,
  last4 text not null,
  expiry_month integer not null,
  expiry_year integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for cards
alter table cards enable row level security;
create policy "Users can manage their own cards." on cards
  for all using (auth.uid() = user_id);

-- Create categories table
DROP TABLE IF EXISTS public.categories CASCADE;
CREATE TABLE public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    slug text NOT NULL,
    description text NULL,
    parent_id bigint NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_key UNIQUE (slug),
    CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE
);
-- RLS for categories
alter table categories enable row level security;
create policy "Categories are viewable by everyone." on categories for select using (true);
create policy "Authenticated users can manage categories." on categories for all using (auth.role() = 'authenticated');
-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';

-- Create tags table
DROP TABLE IF EXISTS public.tags CASCADE;
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  created_at timestamp with time zone not null default now()
);
-- RLS for tags
alter table tags enable row level security;
create policy "Tags are viewable by everyone." on tags for select using (true);
create policy "Authenticated users can manage tags." on tags for all using (auth.role() = 'authenticated');
-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';


-- Create products table
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null,
    description text,
    unit text,
    price numeric not null,
    original_price numeric,
    stock integer not null default 0,
    status text not null default 'draft',
    category_id bigint references public.categories(id) on delete set null,
    featured_image_url text,
    gallery_urls text[],
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Create product_tags table for many-to-many relationship
create table if not exists public.product_tags (
    product_id bigint not null references public.products(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,
    primary key (product_id, tag_id)
);


-- RLS for products and product_tags
alter table public.products enable row level security;
create policy "Products are viewable by everyone." on public.products for select using (true);
create policy "Authenticated users can manage products." on public.products for all using (auth.role() = 'authenticated');

alter table public.product_tags enable row level security;
create policy "Product tags are viewable by everyone." on public.product_tags for select using (true);
create policy "Authenticated users can manage product tags." on public.product_tags for all using (auth.role() = 'authenticated');

-- Function to update updated_at column
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger to update updated_at on product update
create trigger on_product_update
  before update on public.products
  for each row execute procedure public.handle_updated_at();
  
-- Set up storage for product images
insert into storage.buckets (id, name, public)
values ('product_images', 'product_images', true)
on conflict (id) do nothing;

create policy "Product images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'product_images' );

create policy "Authenticated users can upload product images."
  on storage.objects for insert
  with check ( bucket_id = 'product_images' and auth.role() = 'authenticated' );

create policy "Authenticated users can update their own product images."
  on storage.objects for update
  using ( auth.uid() = owner and bucket_id = 'product_images' and auth.role() = 'authenticated' );

create policy "Authenticated users can delete their own product images."
  on storage.objects for delete
  using ( auth.uid() = owner and bucket_id = 'product_images' and auth.role() = 'authenticated' );

-- Add updated_at to profiles if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'profiles'
        AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE public.profiles
        ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();
    END IF;
END;
$$;
