-- Helper function to check if a user is an admin or higher
-- This ensures that only authorized users can manage contact messages.
CREATE OR REPLACE FUNCTION is_admin(user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  SELECT role::text INTO user_role FROM public.profiles WHERE id = user_id;
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 1. Create the contact_messages table to store submissions
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' NOT NULL, -- e.g., 'unread', 'read', 'archived'
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


-- 2. Enable Row Level Security (RLS) on the new table
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;


-- 3. Define RLS Policies
-- Allow anyone to submit a new message (insert)
DROP POLICY IF EXISTS "Allow public insert for contact messages" ON public.contact_messages;
CREATE POLICY "Allow public insert for contact messages" ON public.contact_messages
    FOR INSERT WITH CHECK (true);

-- Allow admins and managers to view all messages
DROP POLICY IF EXISTS "Allow admin select for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin select for contact messages" ON public.contact_messages
    FOR SELECT USING (is_admin(auth.uid()));

-- Allow admins and managers to update message status
DROP POLICY IF EXISTS "Allow admin update for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin update for contact messages" ON public.contact_messages
    FOR UPDATE USING (is_admin(auth.uid()));

-- Allow admins and managers to delete messages
DROP POLICY IF EXISTS "Allow admin delete for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin delete for contact messages" ON public.contact_messages
    FOR DELETE USING (is_admin(auth.uid()));


-- 4. Create a function to securely fetch all messages for the admin dashboard
CREATE OR REPLACE FUNCTION get_contact_messages()
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date
    FROM public.contact_messages cm
    ORDER BY cm.created_at DESC;
END;
$$;

-- 5. Create a function to get a single message's details
CREATE OR REPLACE FUNCTION get_contact_message_details(p_message_id BIGINT)
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ,
    avatar JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date,
        jsonb_build_object(
            'imageUrl', NULL,
            'imageHint', 'person icon'
        ) as avatar
    FROM public.contact_messages cm
    WHERE cm.id = p_message_id;
END;
$$;