-- FULL DATABASE SCRIPT
-- This script is designed to be idempotent and can be run multiple times safely.

-- ----------------------------------------------------------------
-- 1. extensions
-- ----------------------------------------------------------------
create extension if not exists "uuid-ossp" with schema "extensions";
create extension if not exists "moddatetime" with schema "extensions";


-- ----------------------------------------------------------------
-- 2. tables
-- ----------------------------------------------------------------
drop table if exists profiles cascade;
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  bio text,
  contact_number text,
  role text default 'customer'
);

drop table if exists products cascade;
create table products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    name text not null,
    slug text not null,
    description text,
    unit text,
    price double precision not null,
    original_price double precision,
    stock integer default 0,
    status text default 'draft',
    featured_image_url text,
    gallery_urls text[],
    view_count integer default 0
);

drop table if exists categories cascade;
create table categories (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    name text not null,
    slug text not null,
    description text,
    parent_id bigint references categories(id) on delete set null,
    icon text
);

drop table if exists tags cascade;
create table tags (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    name text not null,
    slug text not null
);

drop table if exists product_categories cascade;
create table product_categories (
    product_id bigint references products(id) on delete cascade,
    category_id bigint references categories(id) on delete cascade,
    primary key (product_id, category_id)
);

drop table if exists product_tags cascade;
create table product_tags (
    product_id bigint references products(id) on delete cascade,
    tag_id bigint references tags(id) on delete cascade,
    primary key (product_id, tag_id)
);

drop table if exists orders cascade;
create table orders (
    id bigint generated by default as identity primary key,
    order_number text unique not null,
    created_at timestamp with time zone default now(),
    user_id uuid references auth.users(id),
    total_amount double precision not null,
    status text not null,
    shipping_details jsonb,
    coupon_code text,
    discount_amount double precision,
    payment_method text,
    payment_details jsonb
);

drop table if exists order_items cascade;
create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    product_id bigint references products(id) on delete set null,
    quantity integer not null,
    price_at_purchase double precision not null
);

drop table if exists reviews cascade;
create table reviews (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    user_id uuid references auth.users(id) on delete set null,
    product_id bigint references products(id) on delete cascade,
    rating integer not null check (rating >= 1 and rating <= 5),
    text text,
    status text default 'Pending',
    unique(user_id, product_id)
);

drop table if exists questions cascade;
create table questions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    user_id uuid references auth.users(id) on delete set null,
    product_id bigint references products(id) on delete cascade,
    question_text text not null,
    answer_text text,
    status text default 'Pending',
    answered_at timestamp with time zone
);

drop table if exists wishlist cascade;
create table wishlist (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    product_id bigint references products(id) on delete cascade,
    created_at timestamp with time zone default now(),
    unique(user_id, product_id)
);

drop table if exists addresses cascade;
create table addresses (
    id bigint generated always as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    created_at timestamp with time zone default now(),
    address_type text,
    title text,
    country text,
    city text,
    state text,
    zip text,
    street_address text
);

drop table if exists cards cascade;
create table cards (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    created_at timestamp with time zone default now(),
    card_type text,
    last4 text,
    expiry_month integer,
    expiry_year integer
);

drop table if exists refunds cascade;
create table refunds (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    user_id uuid references auth.users(id) on delete cascade,
    amount double precision,
    reason text,
    status text,
    created_at timestamp with time zone default now()
);

drop table if exists notifications cascade;
create table notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    title text not null,
    message text,
    link text,
    is_read boolean default false,
    created_at timestamp with time zone default now(),
    type text
);

drop table if exists contact_messages cascade;
create table contact_messages (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    subject text,
    message text,
    status text default 'unread',
    created_at timestamp with time zone default now()
);

drop table if exists pages cascade;
create table pages (
    slug text primary key,
    title text,
    content jsonb,
    updated_at timestamp with time zone default now()
);

drop table if exists settings cascade;
create table settings (
    key text primary key,
    value text
);

drop table if exists offers cascade;
create table offers (
    id bigint generated by default as identity primary key,
    title text,
    subtitle text,
    code text unique not null,
    discount_percentage double precision,
    status text,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    image_url text,
    category_ids integer[],
    product_ids integer[],
    created_at timestamp with time zone default now()
);

drop table if exists promos cascade;
create table promos (
    id bigint generated by default as identity primary key,
    title text not null,
    subtitle text,
    image_url text,
    button_text text,
    button_link text,
    status text default 'inactive',
    created_at timestamp with time zone default now()
);

drop table if exists home_page_sections cascade;
create table home_page_sections (
    id bigint generated by default as identity primary key,
    category_id bigint references categories(id) on delete cascade unique,
    display_order integer
);

-- Table for order history/timeline
drop table if exists order_history cascade;
create table order_history (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    status text,
    created_at timestamp with time zone default now()
);

-- ----------------------------------------------------------------
-- 3. types
-- ----------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        create type order_status as enum ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
    END IF;
END$$;


-- ----------------------------------------------------------------
-- 4. triggers and functions
-- ----------------------------------------------------------------

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
DROP FUNCTION IF EXISTS public.handle_new_user();
create function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users for each row
execute procedure public.handle_new_user();


-- This trigger automatically updates the updated_at column when a profile is updated.
DROP FUNCTION IF EXISTS public.handle_update_user();
create function public.handle_update_user() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_profile_updated on public.profiles;
create trigger on_profile_updated
before update on public.profiles for each row
execute procedure public.handle_update_user();


-- Function to get a user's role
DROP FUNCTION IF EXISTS public.get_user_role(p_user_id uuid);
create function public.get_user_role(p_user_id uuid)
returns text
language plpgsql
as $$
declare
  user_role text;
begin
  select role into user_role from public.profiles where id = p_user_id;
  return user_role;
end;
$$;


-- Function to log order status changes to the history table
DROP FUNCTION IF EXISTS public.log_order_status_change();
create function public.log_order_status_change()
returns trigger
language plpgsql
as $$
begin
    -- On insert, log the initial status
    if TG_OP = 'INSERT' then
        insert into order_history (order_id, status)
        values (new.id, new.status);
    -- On update, only log if the status has actually changed
    elsif TG_OP = 'UPDATE' and new.status is distinct from old.status then
        insert into order_history (order_id, status)
        values (new.id, new.status);
    end if;
    return new;
end;
$$;

-- Trigger to log order status change
drop trigger if exists on_order_status_change on public.orders;
create trigger on_order_status_change
after insert or update of status on orders
for each row
execute procedure log_order_status_change();


-- ----------------------------------------------------------------
-- 5. RLS policies
-- ----------------------------------------------------------------
alter table profiles enable row level security;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

alter table reviews enable row level security;
DROP POLICY IF EXISTS "Reviews are public." ON public.reviews;
CREATE POLICY "Reviews are public." ON public.reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert their own reviews." ON public.reviews;
CREATE POLICY "Users can insert their own reviews." ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

alter table questions enable row level security;
DROP POLICY IF EXISTS "questions are public." ON public.questions;
CREATE POLICY "questions are public." ON public.questions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert their own questions." ON public.questions;
CREATE POLICY "Users can insert their own questions." ON public.questions FOR INSERT WITH CHECK (auth.uid() = user_id);

alter table wishlist enable row level security;
DROP POLICY IF EXISTS "Users can view their own wishlist." ON public.wishlist;
CREATE POLICY "Users can view their own wishlist." ON public.wishlist FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own wishlist items." ON public.wishlist;
CREATE POLICY "Users can insert their own wishlist items." ON public.wishlist FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete their own wishlist items." ON public.wishlist;
CREATE POLICY "Users can delete their own wishlist items." ON public.wishlist FOR DELETE USING (auth.uid() = user_id);

alter table addresses enable row level security;
DROP POLICY IF EXISTS "Users can manage their own addresses." ON public.addresses;
CREATE POLICY "Users can manage their own addresses." ON public.addresses FOR ALL USING (auth.uid() = user_id);

alter table cards enable row level security;
DROP POLICY IF EXISTS "Users can manage their own cards." ON public.cards;
CREATE POLICY "Users can manage their own cards." ON public.cards FOR ALL USING (auth.uid() = user_id);

alter table orders enable row level security;
DROP POLICY IF EXISTS "Users can view their own orders." ON public.orders;
CREATE POLICY "Users can view their own orders." ON public.orders FOR SELECT USING (auth.uid() = user_id);

alter table refunds enable row level security;
DROP POLICY IF EXISTS "Users can view their own refunds" ON public.refunds;
CREATE POLICY "Users can view their own refunds" ON public.refunds FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own refund requests" ON public.refunds;
CREATE POLICY "Users can insert their own refund requests" ON public.refunds FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can cancel their own pending refund requests" ON public.refunds;
CREATE POLICY "Users can cancel their own pending refund requests" ON public.refunds FOR DELETE USING (auth.uid() = user_id AND status = 'Pending');

alter table notifications enable row level security;
DROP POLICY IF EXISTS "Users can see their own notifications" ON public.notifications;
CREATE POLICY "Users can see their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins can see admin notifications" ON public.notifications;
CREATE POLICY "Admins can see admin notifications" ON public.notifications FOR SELECT USING (user_id IS NULL);

alter table contact_messages enable row level security;
-- Default policy is to deny all, so only service_role can access unless a policy is defined.

alter table pages enable row level security;
DROP POLICY IF EXISTS "Pages are public" ON public.pages;
CREATE POLICY "Pages are public" ON public.pages FOR SELECT USING (true);

alter table settings enable row level security;
DROP POLICY IF EXISTS "Settings are public" ON public.settings;
CREATE POLICY "Settings are public" ON public.settings FOR SELECT USING (true);

alter table promos enable row level security;
DROP POLICY IF EXISTS "Promos are public" ON public.promos;
CREATE POLICY "Promos are public" ON public.promos FOR SELECT USING (true);

alter table home_page_sections enable row level security;
DROP POLICY IF EXISTS "Home sections are public" ON public.home_page_sections;
CREATE POLICY "Home sections are public" ON public.home_page_sections FOR SELECT USING (true);

alter table offers enable row level security;
DROP POLICY IF EXISTS "Offers are public" ON public.offers;
CREATE POLICY "Offers are public" ON public.offers FOR SELECT USING (true);

alter table order_history enable row level security;


-- ----------------------------------------------------------------
-- 6. custom functions
-- ----------------------------------------------------------------

-- Function to get a user's wishlist IDs.
DROP FUNCTION IF EXISTS public.get_user_wishlist_ids(uuid);
CREATE OR REPLACE FUNCTION public.get_user_wishlist_ids(p_user_id uuid)
RETURNS TABLE (product_id integer)
LANGUAGE sql
SECURITY DEFINER
AS $$
  select product_id from public.wishlist where user_id = p_user_id;
$$;

-- Function to toggle a wishlist item.
DROP FUNCTION IF EXISTS public.toggle_wishlist_item(uuid, integer);
CREATE OR REPLACE FUNCTION public.toggle_wishlist_item(p_user_id uuid, p_product_id integer)
RETURNS json
LANGUAGE plpgsql
AS $$
DECLARE
  v_wishlist_id bigint;
  v_status text;
BEGIN
  -- Check if the item already exists
  SELECT id INTO v_wishlist_id
  FROM public.wishlist
  WHERE user_id = p_user_id AND product_id = p_product_id;

  IF v_wishlist_id IS NOT NULL THEN
    -- Item exists, so delete it
    DELETE FROM public.wishlist WHERE id = v_wishlist_id;
    v_status := 'removed';
  ELSE
    -- Item does not exist, so insert it
    INSERT INTO public.wishlist (user_id, product_id)
    VALUES (p_user_id, p_product_id);
    v_status := 'added';
  END IF;

  RETURN json_build_object('status', v_status);
END;
$$;


-- Function to get all users with their roles.
DROP FUNCTION IF EXISTS public.get_all_users();
CREATE OR REPLACE FUNCTION public.get_all_users()
RETURNS TABLE (
    id uuid,
    full_name text,
    email text,
    avatar_url text,
    created_at timestamp with time zone,
    role text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    select
        u.id,
        p.full_name,
        u.email,
        p.avatar_url,
        u.created_at,
        p.role
    from auth.users u
    left join public.profiles p on u.id = p.id;
$$;


-- Function to get all settings as a single JSON object.
DROP FUNCTION IF EXISTS public.get_all_settings();
CREATE OR REPLACE FUNCTION public.get_all_settings()
RETURNS jsonb
LANGUAGE sql
AS $$
    SELECT jsonb_object_agg(key, value)
    FROM public.settings;
$$;


-- Function to get order history.
DROP FUNCTION IF EXISTS public.get_order_history(bigint);
CREATE OR REPLACE FUNCTION public.get_order_history(p_order_id bigint)
RETURNS TABLE (
    status text,
    created_at timestamp with time zone
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    select status, created_at
    from public.order_history
    where order_id = p_order_id
    order by created_at asc;
$$;


-- Function to update home page sections in a transaction.
DROP FUNCTION IF EXISTS public.update_home_sections(jsonb);
CREATE OR REPLACE FUNCTION public.update_home_sections(sections_data jsonb)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- Clear existing sections
    DELETE FROM public.home_page_sections;

    -- Insert new sections from the JSONB array
    INSERT INTO public.home_page_sections (category_id, display_order)
    SELECT
        (elem->>'category_id')::bigint,
        (elem->>'display_order')::integer
    FROM jsonb_array_elements(sections_data) elem;
END;
$$;

-- Function to increment a product's view count.
DROP FUNCTION IF EXISTS public.increment_product_view(integer);
CREATE OR REPLACE FUNCTION public.increment_product_view(product_id_to_inc integer)
RETURNS void
LANGUAGE sql
AS $$
    update products
    set view_count = view_count + 1
    where id = product_id_to_inc;
$$;


-- Combined function to create an order and its items.
DROP FUNCTION IF EXISTS public.create_order(double precision, jsonb, jsonb, text, jsonb, double precision, text, text);
CREATE OR REPLACE FUNCTION public.create_order(
    p_total_amount double precision,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_discount_amount double precision,
    p_coupon_code text,
    p_initial_status text
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id bigint;
    v_order_number text;
    item jsonb;
BEGIN
    -- Generate a unique order number
    v_order_number := 'KB-' || to_char(now(), 'YYYYMMDD') || '-' || (
        SELECT lpad( (count(*) + 1)::text, 4, '0')
        FROM orders
        WHERE created_at >= date_trunc('day', now())
    );

    -- Insert into orders table
    INSERT INTO public.orders (
        user_id, total_amount, status, shipping_details, order_number,
        payment_method, payment_details, discount_amount, coupon_code
    )
    VALUES (
        auth.uid(), p_total_amount, p_initial_status, p_shipping_details, v_order_number,
        p_payment_method, p_transaction_details, p_discount_amount, p_coupon_code
    ) RETURNING id INTO v_order_id;

    -- Loop through items and insert into order_items
    FOR item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (v_order_id, (item->>'product_id')::bigint, (item->>'quantity')::int, (item->>'price')::double precision);

        -- Decrement stock
        UPDATE public.products
        SET stock = stock - (item->>'quantity')::int
        WHERE id = (item->>'product_id')::bigint;
    END LOOP;

    RETURN v_order_number;
END;
$$;


-- Function to update order status and log history, returning key order info for notifications
DROP FUNCTION IF EXISTS public.update_order_status_and_log(bigint, text);
CREATE OR REPLACE FUNCTION public.update_order_status_and_log(
    p_order_id bigint,
    p_new_status text
)
RETURNS TABLE (
    user_id uuid,
    order_number text
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    UPDATE public.orders
    SET status = p_new_status
    WHERE id = p_order_id
    RETURNING public.orders.user_id, public.orders.order_number;
END;
$$;

-- Function to get admin notifications
DROP FUNCTION IF EXISTS public.get_admin_notifications();
CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS SETOF notifications
LANGUAGE sql
SECURITY DEFINER
AS $$
  select * from public.notifications where user_id is null order by created_at desc;
$$;


-- Function to get admin reviews
DROP FUNCTION IF EXISTS public.get_admin_reviews();
CREATE OR REPLACE FUNCTION public.get_admin_reviews()
RETURNS TABLE (
    id bigint,
    rating integer,
    text text,
    status text,
    created_at timestamp with time zone,
    author json,
    product json
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        r.id,
        r.rating,
        r.text,
        r.status,
        r.created_at,
        json_build_object(
            'name', p.full_name,
            'avatar_url', p.avatar_url
        ) as author,
        json_build_object(
            'id', prod.id,
            'name', prod.name,
            'featured_image_url', prod.featured_image_url
        ) as product
    FROM reviews r
    LEFT JOIN profiles p ON r.user_id = p.id
    LEFT JOIN products prod ON r.product_id = prod.id
    ORDER BY r.created_at DESC;
$$;

-- Function to get admin questions
DROP FUNCTION IF EXISTS public.get_admin_questions();
CREATE OR REPLACE FUNCTION public.get_admin_questions()
RETURNS TABLE (
    id bigint,
    question text,
    answer text,
    status text,
    date timestamp with time zone,
    author json,
    product json
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        q.id,
        q.question_text as question,
        q.answer_text as answer,
        q.status,
        q.created_at as date,
        json_build_object(
            'name', p.full_name,
            'avatar', json_build_object('imageUrl', p.avatar_url, 'imageHint', 'person face')
        ) as author,
        json_build_object(
            'id', prod.id,
            'name', prod.name,
            'image', json_build_object('imageUrl', prod.featured_image_url, 'imageHint', 'product')
        ) as product
    FROM questions q
    LEFT JOIN profiles p ON q.user_id = p.id
    LEFT JOIN products prod ON q.product_id = prod.id
    ORDER BY q.created_at DESC;
$$;


-- Function to get admin refunds
DROP FUNCTION IF EXISTS public.get_admin_refunds();
CREATE OR REPLACE FUNCTION public.get_admin_refunds()
RETURNS TABLE (
    id bigint,
    order_id bigint,
    order_number text,
    amount double precision,
    status text,
    reason text,
    created_at timestamp with time zone,
    user_id uuid,
    customer_name text,
    customer_avatar_url text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        r.id,
        r.order_id,
        o.order_number,
        r.amount,
        r.status,
        r.reason,
        r.created_at,
        r.user_id,
        p.full_name as customer_name,
        p.avatar_url as customer_avatar_url
    FROM refunds r
    LEFT JOIN orders o ON r.order_id = o.id
    LEFT JOIN profiles p ON r.user_id = p.id
    ORDER BY r.created_at DESC;
$$;


-- Function to get admin order list
DROP FUNCTION IF EXISTS public.get_admin_order_list();
CREATE OR REPLACE FUNCTION public.get_admin_order_list()
RETURNS TABLE(
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount double precision,
    status text,
    customer_name text,
    customer_email text,
    customer_avatar_url text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT
    o.id,
    o.order_number,
    o.created_at,
    o.total_amount,
    o.status,
    p.full_name as customer_name,
    o.shipping_details->>'email' as customer_email,
    p.avatar_url as customer_avatar_url
  FROM orders o
  LEFT JOIN profiles p ON o.user_id = p.id
  ORDER BY o.created_at DESC;
$$;


-- Function to get product reviews with author details.
DROP FUNCTION IF EXISTS public.get_product_reviews(bigint);
CREATE OR REPLACE FUNCTION public.get_product_reviews(p_product_id bigint)
RETURNS TABLE (
    id bigint,
    rating integer,
    text text,
    created_at timestamp with time zone,
    author_name text,
    author_avatar text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.id,
        r.rating,
        r.text,
        r.created_at,
        p.full_name as author_name,
        p.avatar_url as author_avatar
    FROM reviews r
    JOIN profiles p ON r.user_id = p.id
    WHERE r.product_id = p_product_id AND r.status = 'Approved'
    ORDER BY r.created_at DESC;
END;
$$;

-- Function to get product rating stats
DROP FUNCTION IF EXISTS public.get_product_rating_stats(bigint);
CREATE OR REPLACE FUNCTION public.get_product_rating_stats(p_product_id bigint)
RETURNS TABLE (
    total_reviews bigint,
    avg_rating numeric,
    rating_distribution jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*) as total_reviews,
        COALESCE(AVG(rating), 0) as avg_rating,
        jsonb_agg(
            jsonb_build_object('rating', rating, 'count', count)
        ) as rating_distribution
    FROM (
        SELECT
            rating,
            COUNT(*) as count
        FROM reviews
        WHERE product_id = p_product_id AND status = 'Approved'
        GROUP BY rating
    ) as rating_counts;
END;
$$;


-- Function to get product questions with author details.
DROP FUNCTION IF EXISTS public.get_product_questions(bigint);
CREATE OR REPLACE FUNCTION public.get_product_questions(p_product_id bigint)
RETURNS TABLE (
    id bigint,
    question_text text,
    answer_text text,
    created_at timestamp with time zone,
    author_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        q.id,
        q.question_text,
        q.answer_text,
        q.created_at,
        p.full_name as author_name
    FROM questions q
    JOIN profiles p ON q.user_id = p.id
    WHERE q.product_id = p_product_id AND q.status = 'Answered'
    ORDER BY q.created_at DESC;
END;
$$;

-- Function to get contact messages
DROP FUNCTION IF EXISTS public.get_contact_messages();
CREATE OR REPLACE FUNCTION public.get_contact_messages()
RETURNS TABLE (
    id bigint,
    senderName text,
    senderemail text,
    subject text,
    message text,
    date text,
    status text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderemail,
        cm.subject,
        cm.message,
        cm.created_at::text as date,
        cm.status
    FROM contact_messages cm
    ORDER BY cm.created_at DESC;
END;
$$;


-- Function to get details for a single contact message
DROP FUNCTION IF EXISTS public.get_contact_message_details(bigint);
CREATE OR REPLACE FUNCTION public.get_contact_message_details(p_message_id bigint)
RETURNS TABLE (
    id bigint,
    senderName text,
    senderEmail text,
    subject text,
    message text,
    date text,
    status text,
    avatar json
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.created_at::text as date,
        cm.status,
        json_build_object('imageUrl', null, 'imageHint', 'person face') as avatar
    FROM contact_messages cm
    WHERE cm.id = p_message_id;
END;
$$;

-- Function to get user's questions
DROP FUNCTION IF EXISTS public.get_user_questions(uuid);
CREATE OR REPLACE FUNCTION public.get_user_questions(p_user_id uuid)
RETURNS TABLE (
    id bigint,
    question_text text,
    answer_text text,
    status text,
    created_at timestamp with time zone,
    product_name text,
    product_id bigint,
    product_image text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        q.id,
        q.question_text,
        q.answer_text,
        q.status,
        q.created_at,
        p.name as product_name,
        p.id as product_id,
        p.featured_image_url as product_image
    FROM questions q
    JOIN products p ON q.product_id = p.id
    WHERE q.user_id = p_user_id
    ORDER BY q.created_at DESC;
$$;

-- Function to get user's reviews
DROP FUNCTION IF EXISTS public.get_user_reviews(uuid);
CREATE OR REPLACE FUNCTION public.get_user_reviews(p_user_id uuid)
RETURNS TABLE (
    id bigint,
    rating integer,
    text text,
    status text,
    created_at timestamp with time zone,
    product_name text,
    product_image text,
    product_id bigint
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        r.id,
        r.rating,
        r.text,
        r.status,
        r.created_at,
        p.name as product_name,
        p.featured_image_url as product_image,
        p.id as product_id
    FROM reviews r
    JOIN products p ON r.product_id = p.id
    WHERE r.user_id = p_user_id
    ORDER BY r.created_at DESC;
$$;


-- Function to get user's refunds
DROP FUNCTION IF EXISTS public.get_user_refunds(uuid);
CREATE OR REPLACE FUNCTION public.get_user_refunds(p_user_id uuid)
RETURNS TABLE (
    id bigint,
    order_id bigint,
    order_number text,
    amount double precision,
    status text,
    reason text,
    created_at timestamp with time zone
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        r.id,
        r.order_id,
        o.order_number,
        r.amount,
        r.status,
        r.reason,
        r.created_at
    FROM refunds r
    LEFT JOIN orders o ON r.order_id = o.id
    WHERE r.user_id = p_user_id
    ORDER BY r.created_at DESC;
$$;

-- Function to get user's transactions
DROP FUNCTION IF EXISTS public.get_user_transactions(uuid);
CREATE OR REPLACE FUNCTION public.get_user_transactions(p_user_id uuid)
RETURNS TABLE(
    id bigint,
    order_id bigint,
    order_number text,
    amount double precision,
    payment_method text,
    status text,
    created_at timestamp with time zone
)
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT
    o.id,
    o.id as order_id,
    o.order_number,
    o.total_amount as amount,
    o.payment_method,
    CASE
        WHEN o.status = 'Processing' THEN 'Completed'
        WHEN o.status = 'Failed' THEN 'Failed'
        ELSE 'Pending'
    END as status,
    o.created_at
  FROM orders o
  WHERE o.user_id = p_user_id AND o.payment_method IS NOT NULL
  ORDER BY o.created_at DESC;
$$;


-- Function to get category tree
DROP FUNCTION IF EXISTS public.get_category_tree();
CREATE OR REPLACE FUNCTION public.get_category_tree()
RETURNS TABLE (name text, subcategories text[])
LANGUAGE sql
AS $$
    with parent_cats as (
        select id, name from categories where parent_id is null
    )
    select
        pc.name,
        array_agg(c.name) as subcategories
    from parent_cats pc
    join categories c on c.parent_id = pc.id
    group by pc.name;
$$;


-- Function to get related products (More resilient version)
DROP FUNCTION IF EXISTS get_related_products(integer, integer);
CREATE OR REPLACE FUNCTION get_related_products(p_id integer, p_limit integer)
RETURNS SETOF products AS $$
BEGIN
    RETURN QUERY
    WITH product_details AS (
        SELECT
            (SELECT array_agg(category_id) FROM product_categories WHERE product_id = p_id) as cats,
            (SELECT array_agg(tag_id) FROM product_tags WHERE product_id = p_id) as tags,
            (SELECT category_id FROM product_categories WHERE product_id = p_id LIMIT 1) as main_cat
    ),
    scored_products AS (
        SELECT
            p.id,
            (
                (SELECT COUNT(*) FROM product_categories pc WHERE pc.product_id = p.id AND pc.category_id = ANY((SELECT cats FROM product_details))) * 2
            ) +
            (
                (SELECT COUNT(*) FROM product_tags pt WHERE pt.product_id = p.id AND pt.tag_id = ANY((SELECT tags FROM product_details)))
            ) as relevance_score
        FROM products p
        WHERE p.id != p_id AND p.status = 'active'
    )
    (
        SELECT p.*
        FROM products p
        JOIN scored_products s ON p.id = s.id
        WHERE s.relevance_score > 0
        ORDER BY s.relevance_score DESC, p.view_count DESC NULLS LAST
        LIMIT p_limit
    )
    UNION
    (
        SELECT p.*
        FROM products p
        JOIN product_categories pc on p.id = pc.product_id
        WHERE p.id != p_id
            AND p.status = 'active'
            AND pc.category_id = (SELECT main_cat FROM product_details)
            AND p.id NOT IN (SELECT id FROM products p JOIN scored_products s ON p.id = s.id WHERE s.relevance_score > 0)
        ORDER BY p.view_count DESC NULLS LAST
        LIMIT p_limit
    )
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;


-- Function to get recommended products (More resilient version)
DROP FUNCTION IF EXISTS get_recommended_products(integer);
CREATE OR REPLACE FUNCTION public.get_recommended_products(p_limit integer)
RETURNS SETOF products
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    WITH product_scores AS (
        SELECT
            p.id,
            COALESCE((SELECT COUNT(*) FROM order_items oi WHERE oi.product_id = p.id), 0) as sales_count,
            COALESCE((SELECT COUNT(*) FROM wishlist w WHERE w.product_id = p.id), 0) as wishlist_count,
            COALESCE(p.view_count, 0) as view_count,
            p.created_at
        FROM
            products p
        WHERE p.status = 'active'
    ),
    ranked_products AS (
        SELECT
            ps.id,
            -- Weighted score: Sales (50%), Wishlists (30%), Views (20%)
            (ps.sales_count * 0.5) + (ps.wishlist_count * 0.3) + (ps.view_count * 0.2) as score,
            ps.created_at
        FROM
            product_scores ps
    )
    (
        SELECT p.*
        FROM products p
        JOIN ranked_products rp ON p.id = rp.id
        WHERE rp.score > 0
        ORDER BY rp.score DESC, p.created_at DESC
        LIMIT p_limit
    )
    UNION
    (
        SELECT p.*
        FROM products p
        WHERE p.status = 'active'
        AND p.id NOT IN (SELECT id FROM ranked_products WHERE score > 0)
        ORDER BY p.created_at DESC
        LIMIT p_limit
    )
    LIMIT p_limit;
END;
$$;


-- Function to get admin order details
DROP FUNCTION IF EXISTS public.get_admin_order_details(text);
CREATE OR REPLACE FUNCTION public.get_admin_order_details(p_order_number text)
RETURNS TABLE (
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount double precision,
    status text,
    shipping_details jsonb,
    profiles jsonb,
    order_items jsonb,
    coupon_code text,
    discount_amount double precision,
    payment_method text,
    transaction_details jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details,
        jsonb_build_object('full_name', p.full_name, 'avatar_url', p.avatar_url) as profiles,
        (SELECT jsonb_agg(
            jsonb_build_object(
                'id', oi.id,
                'quantity', oi.quantity,
                'price_at_purchase', oi.price_at_purchase,
                'products', jsonb_build_object(
                    'name', pr.name,
                    'featured_image_url', pr.featured_image_url
                )
            )
        ) FROM order_items oi JOIN products pr ON oi.product_id = pr.id WHERE oi.order_id = o.id) as order_items,
        o.coupon_code,
        o.discount_amount,
        o.payment_method,
        o.payment_details as transaction_details
    FROM orders o
    LEFT JOIN profiles p ON o.user_id = p.id
    WHERE o.order_number = p_order_number;
END;
$$;

-- Function to get admin question details
DROP FUNCTION IF EXISTS public.get_admin_question_details(bigint);
CREATE OR REPLACE FUNCTION public.get_admin_question_details(p_question_id bigint)
RETURNS TABLE (
    id bigint,
    question text,
    answer text,
    status text,
    date timestamp with time zone,
    author json,
    product json
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        q.id,
        q.question_text as question,
        q.answer_text as answer,
        q.status,
        q.created_at as date,
        json_build_object(
            'name', p.full_name,
            'avatar', json_build_object('imageUrl', p.avatar_url, 'imageHint', 'person face')
        ) as author,
        json_build_object(
            'id', prod.id,
            'name', prod.name,
            'image', json_build_object('imageUrl', prod.featured_image_url, 'imageHint', 'product')
        ) as product
    FROM questions q
    LEFT JOIN profiles p ON q.user_id = p.id
    LEFT JOIN products prod ON q.product_id = prod.id
    WHERE q.id = p_question_id;
END;
$$;
