-- =================================================================
-- MASTER DATABASE SETUP SCRIPT
-- Purpose: Resets and configures all custom database objects.
-- Run this entire script in the Supabase SQL Editor.
-- =================================================================

-- -----------------------------------------------------------------
-- STAGE 1: DROP EXISTING OBJECTS TO PREVENT CONFLICTS
-- -----------------------------------------------------------------

-- Temporarily disable RLS on tables to drop policies
ALTER TABLE public.contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions DISABLE ROW LEVEL SECURITY;

-- Drop all known functions with CASCADE to handle dependencies
DROP FUNCTION IF EXISTS public.create_new_review_notification() CASCADE;
DROP FUNCTION IF EXISTS public.create_new_contact_message_notification() CASCADE;
DROP FUNCTION IF EXISTS public.create_new_order_notification() CASCADE;
DROP FUNCTION IF EXISTS public.get_admin_notifications() CASCADE;
DROP FUNCTION IF EXISTS public.get_admin_orders() CASCADE;
DROP FUNCTION IF EXISTS public.get_all_users() CASCADE;
DROP FUNCTION IF EXISTS public.get_admins() CASCADE;
DROP FUNCTION IF EXISTS public.get_potential_admins() CASCADE;
DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
DROP FUNCTION IF EXISTS public.get_all_settings() CASCADE;
DROP FUNCTION IF EXISTS public.get_category_tree() CASCADE;
DROP FUNCTION IF EXISTS public.update_home_sections(jsonb) CASCADE;
DROP FUNCTION IF EXISTS public.is_admin(uuid) CASCADE; -- This is the key one causing issues

-- Drop triggers manually before dropping functions they use
DROP TRIGGER IF EXISTS on_new_order ON public.orders;
DROP TRIGGER IF EXISTS on_new_review ON public.reviews;
DROP TRIGGER IF EXISTS on_new_contact_message ON public.contact_messages;

-- Drop and recreate the notifications table
DROP TABLE IF EXISTS public.notifications;
CREATE TABLE public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id) on delete set null,
    title text not null,
    message text,
    link text,
    type text,
    is_read boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
COMMENT ON TABLE public.notifications IS 'Stores notifications for admin users.';

-- -----------------------------------------------------------------
-- STAGE 2: RECREATE FUNCTIONS AND POLICIES
-- -----------------------------------------------------------------

-- Recreate the core is_admin function first
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  SELECT role INTO user_role FROM public.profiles WHERE id = p_user_id;
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-enable RLS and recreate policies
-- Contact Messages
CREATE POLICY "Allow admin select for contact messages" ON public.contact_messages FOR SELECT TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "Allow admin update for contact messages" ON public.contact_messages FOR UPDATE TO authenticated USING (is_admin(auth.uid()));
CREATE POLICY "Allow admin delete for contact messages" ON public.contact_messages FOR DELETE TO authenticated USING (is_admin(auth.uid()));
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Settings
CREATE POLICY "Allow admin full access to settings" ON public.settings FOR ALL TO authenticated USING (is_admin(auth.uid()));
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Orders
CREATE POLICY "Allow individual read access" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow admin full access" ON public.orders FOR ALL USING (is_admin(auth.uid()));
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Reviews
CREATE POLICY "Allow individual insert" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow public read for approved reviews" ON public.reviews FOR SELECT USING (status = 'Approved'::review_status);
CREATE POLICY "Allow admin full access" ON public.reviews FOR ALL USING (is_admin(auth.uid()));
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Questions
CREATE POLICY "Allow individual insert" ON public.questions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow public read" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.questions FOR ALL USING (is_admin(auth.uid()));
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Notifications
CREATE POLICY "Allow admin read access" ON public.notifications FOR SELECT TO authenticated USING (is_admin(auth.uid()));
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------
-- STAGE 3: RECREATE NOTIFICATION SYSTEM
-- -----------------------------------------------------------------

-- Notification Trigger Functions
CREATE OR REPLACE FUNCTION public.create_new_order_notification()
RETURNS TRIGGER AS $$
DECLARE
  profile_name TEXT;
BEGIN
  SELECT full_name INTO profile_name FROM public.profiles WHERE id = NEW.user_id;
  INSERT INTO public.notifications (user_id, title, message, link, type)
  VALUES (
    NEW.user_id,
    'New Order Received',
    COALESCE(profile_name, (NEW.shipping_details ->> 'firstName') || ' ' || (NEW.shipping_details ->> 'lastName'), 'A user') || ' placed order ' || NEW.order_number,
    '/admin/orders/' || NEW.order_number,
    'new_order'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.create_new_review_notification()
RETURNS TRIGGER AS $$
DECLARE
  profile_name TEXT;
  product_name TEXT;
BEGIN
  SELECT full_name INTO profile_name FROM public.profiles WHERE id = NEW.user_id;
  SELECT name INTO product_name FROM public.products WHERE id = NEW.product_id;
  INSERT INTO public.notifications (user_id, title, message, link, type)
  VALUES (
    NEW.user_id,
    'New Review Submitted',
    COALESCE(profile_name, 'A user') || ' reviewed ' || product_name,
    '/admin/reviews',
    'new_review'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.create_new_contact_message_notification()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notifications (title, message, link, type)
  VALUES (
    'New Contact Message',
    'From: ' || NEW.name,
    '/admin/messages/view/' || NEW.id,
    'new_message'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Recreate Triggers
CREATE TRIGGER on_new_order AFTER INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION public.create_new_order_notification();
CREATE TRIGGER on_new_review AFTER INSERT ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.create_new_review_notification();
CREATE TRIGGER on_new_contact_message AFTER INSERT ON public.contact_messages FOR EACH ROW EXECUTE FUNCTION public.create_new_contact_message_notification();


-- -----------------------------------------------------------------
-- STAGE 4: RECREATE RPC FUNCTIONS
-- -----------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS TABLE (
  id bigint,
  title text,
  message text,
  link text,
  is_read boolean,
  created_at timestamp with time zone,
  type text
) AS $$
BEGIN
  IF is_admin(auth.uid()) THEN
    RETURN QUERY
    SELECT
      n.id,
      n.title,
      n.message,
      n.link,
      n.is_read,
      n.created_at,
      n.type
    FROM
      public.notifications n
    ORDER BY
      n.created_at DESC
    LIMIT 50;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Add back other RPC functions that might have been dropped
-- It is safer to recreate them.
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TABLE(role text) AS $$
BEGIN
  RETURN QUERY
  SELECT p.role FROM public.profiles p WHERE p.id = auth.uid();
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.get_admin_orders()
RETURNS TABLE (
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, (o.shipping_details ->> 'firstName') || ' ' || (o.shipping_details ->> 'lastName')) AS customer_name,
        COALESCE(u.email, o.shipping_details ->> 'email') as customer_email,
        p.avatar_url AS customer_avatar_url
    FROM
        public.orders o
    LEFT JOIN
        public.profiles p ON o.user_id = p.id
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    ORDER BY
        o.created_at DESC;
END;
$$ LANGUAGE plpgsql;

