-- =================================================================
-- This script sets up the entire database schema for the application.
-- It is designed to be run in its entirety.
-- =================================================================

-- 1. PROFILES & USER MANAGEMENT
-- =================================================================
-- Create a table for public profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  contact_number TEXT,
  role TEXT DEFAULT 'customer'
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- This trigger automatically creates a profile entry when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url',
    'customer'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if it exists, then create it
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Helper function to check if a user is an admin or higher
CREATE OR REPLACE FUNCTION is_admin(user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  SELECT role::text INTO user_role FROM public.profiles WHERE id = user_id;
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. SETTINGS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access for settings" ON public.settings;
CREATE POLICY "Allow public read access for settings" ON public.settings
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin update for settings" ON public.settings;
CREATE POLICY "Allow admin update for settings" ON public.settings
    FOR UPDATE USING (is_admin(auth.uid()));

-- Function to get all settings as a single JSON object
CREATE OR REPLACE FUNCTION get_all_settings()
RETURNS JSONB AS $$
DECLARE
    settings_json JSONB;
BEGIN
    SELECT jsonb_object_agg(key, value)
    INTO settings_json
    FROM public.settings;
    RETURN settings_json;
END;
$$ LANGUAGE plpgsql;


-- 3. CONTACT MESSAGES
-- =================================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert for contact messages" ON public.contact_messages;
CREATE POLICY "Allow public insert for contact messages" ON public.contact_messages
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin select for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin select for contact messages" ON public.contact_messages
    FOR SELECT USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admin update for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin update for contact messages" ON public.contact_messages
    FOR UPDATE USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admin delete for contact messages" ON public.contact_messages;
CREATE POLICY "Allow admin delete for contact messages" ON public.contact_messages
    FOR DELETE USING (is_admin(auth.uid()));


-- 4. ORDERS & TRANSACTIONS
-- =================================================================
-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_number TEXT UNIQUE NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL,
    shipping_details JSONB NOT NULL,
    coupon_code TEXT,
    discount_amount NUMERIC(10, 2),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL, -- No direct FK to allow product deletion without breaking order history
    quantity INT NOT NULL,
    price_at_purchase NUMERIC(10, 2) NOT NULL
);

-- Create transactions table with NULLABLE user_id
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- <<<<<<<<<<<< FIX: Allow NULL
    amount NUMERIC(10, 2) NOT NULL,
    payment_method TEXT NOT NULL,
    status TEXT NOT NULL,
    transaction_details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- Ensure user_id can be NULL
ALTER TABLE public.transactions ALTER COLUMN user_id DROP NOT NULL;


-- Enable RLS for tables
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Policies for orders
DROP POLICY IF EXISTS "Users can view their own orders" ON public.orders;
CREATE POLICY "Users can view their own orders" ON public.orders
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all orders" ON public.orders;
CREATE POLICY "Admins can manage all orders" ON public.orders
    FOR ALL USING (is_admin(auth.uid()));

-- Policies for order_items (users can view items for orders they own)
DROP POLICY IF EXISTS "Users can view their own order items" ON public.order_items;
CREATE POLICY "Users can view their own order items" ON public.order_items
    FOR SELECT USING (
        (SELECT user_id FROM public.orders WHERE id = order_id) = auth.uid()
    );

DROP POLICY IF EXISTS "Admins can manage all order items" ON public.order_items;
CREATE POLICY "Admins can manage all order items" ON public.order_items
    FOR ALL USING (is_admin(auth.uid()));

-- Policies for transactions
DROP POLICY IF EXISTS "Users can view their own transactions" ON public.transactions;
CREATE POLICY "Users can view their own transactions" ON public.transactions
    FOR SELECT USING (auth.uid() = user_id);
    
DROP POLICY IF EXISTS "Admins can manage all transactions" ON public.transactions;
CREATE POLICY "Admins can manage all transactions" ON public.transactions
    FOR ALL USING (is_admin(auth.uid()));

-- Function to create a new order
CREATE OR REPLACE FUNCTION create_order(
    p_user_id UUID,
    p_total_amount NUMERIC,
    p_shipping_details JSONB,
    p_items JSONB,
    p_payment_method TEXT,
    p_transaction_details JSONB,
    p_coupon_code TEXT,
    p_discount_amount NUMERIC
) RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    new_order_id BIGINT;
    new_order_number TEXT;
    item JSONB;
BEGIN
    -- Generate a unique order number
    new_order_number := 'PB-' || to_char(NOW(), 'YYMMDD') || '-' || substr(md5(random()::text), 1, 6);

    -- Insert into orders table
    INSERT INTO public.orders (user_id, order_number, total_amount, status, shipping_details, coupon_code, discount_amount)
    VALUES (p_user_id, new_order_number, p_total_amount, 'Pending', p_shipping_details, p_coupon_code, p_discount_amount)
    RETURNING id INTO new_order_id;

    -- Insert into order_items table
    FOR item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (new_order_id, (item->>'product_id')::BIGINT, (item->>'quantity')::INT, (item->>'price')::NUMERIC);
    END LOOP;

    -- Insert into transactions table
    INSERT INTO public.transactions(order_id, user_id, amount, payment_method, status, transaction_details)
    VALUES (new_order_id, p_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);

    RETURN new_order_number;
END;
$$;

-- 5. RPC FUNCTIONS FOR ADMIN DASHBOARD
-- =================================================================
-- Get all users with their roles
CREATE OR REPLACE FUNCTION get_all_users()
RETURNS TABLE (
    id UUID,
    full_name TEXT,
    email TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ,
    role TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        u.id,
        p.full_name,
        u.email,
        p.avatar_url,
        u.created_at,
        p.role
    FROM auth.users u
    LEFT JOIN public.profiles p ON u.id = p.id
    ORDER BY u.created_at DESC;
END;
$$;


-- Get all contact messages
CREATE OR REPLACE FUNCTION get_contact_messages()
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Only admins can access contact messages.';
    END IF;

    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date
    FROM public.contact_messages cm
    ORDER BY cm.created_at DESC;
END;
$$;

-- Get details for a single contact message
CREATE OR REPLACE FUNCTION get_contact_message_details(p_message_id BIGINT)
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ,
    avatar JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Only admins can access contact messages.';
    END IF;
    
    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date,
        jsonb_build_object(
            'imageUrl', NULL,
            'imageHint', 'person icon'
        ) as avatar
    FROM public.contact_messages cm
    WHERE cm.id = p_message_id;
END;
$$;

-- Get all orders for admin
CREATE OR REPLACE FUNCTION get_admin_orders()
RETURNS TABLE (
    id BIGINT,
    user_id UUID,
    order_number TEXT,
    created_at TIMESTAMPTZ,
    total_amount NUMERIC,
    status TEXT,
    shipping_details JSONB,
    customer_avatar_url TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Only admins can access orders.';
    END IF;

    RETURN QUERY
    SELECT
        o.id,
        o.user_id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details,
        p.avatar_url as customer_avatar_url
    FROM public.orders o
    LEFT JOIN public.profiles p ON o.user_id = p.id
    ORDER BY o.created_at DESC;
END;
$$;

-- Get guest orders
CREATE OR REPLACE FUNCTION get_guest_orders()
RETURNS TABLE (
    id BIGINT,
    order_number TEXT,
    created_at TIMESTAMPTZ,
    total_amount NUMERIC,
    status TEXT,
    shipping_details JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Only admins can access guest orders.';
    END IF;

    RETURN QUERY
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details
    FROM public.orders o
    WHERE o.user_id IS NULL
    ORDER BY o.created_at DESC;
END;
$$;
