-- Drop existing functions to avoid conflicts and ensure a clean slate for order processing.
DROP FUNCTION IF EXISTS public.log_order_status_change();
DROP FUNCTION IF EXISTS public.update_order_status_and_log(integer, text);
DROP FUNCTION IF EXISTS public.create_order(numeric, jsonb, jsonb, text, jsonb, text, numeric, order_status);
DROP FUNCTION IF EXISTS public.get_admin_order_details(text);

-- Create the order_history table if it doesn't exist to track status changes.
CREATE TABLE IF NOT EXISTS public.order_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    status public.order_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Function to automatically log order status changes into the order_history table.
CREATE OR REPLACE FUNCTION public.log_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if the status is actually being changed to avoid duplicate history entries.
    IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO public.order_history(order_id, status)
        VALUES (NEW.id, NEW.status);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute the logging function whenever an order's status is updated or a new order is inserted.
DROP TRIGGER IF EXISTS log_order_status_change_trigger ON public.orders;
CREATE TRIGGER log_order_status_change_trigger
AFTER INSERT OR UPDATE OF status ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.log_order_status_change();

-- Function for admins to update an order's status.
CREATE OR REPLACE FUNCTION public.update_order_status_and_log(p_order_id integer, p_new_status text)
RETURNS TABLE(user_id uuid, order_number text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.orders
    SET status = p_new_status::public.order_status
    WHERE id = p_order_id;

    RETURN QUERY
    SELECT o.user_id, o.order_number
    FROM public.orders o
    WHERE o.id = p_order_id;
END;
$$;

-- Corrected function to create a new order, ensuring product_id is correctly referenced.
CREATE OR REPLACE FUNCTION public.create_order(
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric,
    p_initial_status public.order_status DEFAULT 'Pending'::public.order_status
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    new_order_id bigint;
    new_order_number text;
    item jsonb;
    auth_user_id uuid := auth.uid();
BEGIN
    -- 1. Create the order
    INSERT INTO public.orders (user_id, total_amount, status, shipping_details, coupon_code, discount_amount, payment_method)
    VALUES (auth_user_id, p_total_amount, p_initial_status, p_shipping_details, p_coupon_code, p_discount_amount, p_payment_method)
    RETURNING id, order_number INTO new_order_id, new_order_number;

    -- 2. Insert order items
    FOR item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (new_order_id, (item->>'id')::bigint, (item->>'quantity')::int, (item->>'price')::numeric);
    END LOOP;

    -- 3. Create transaction record
    IF p_transaction_details IS NOT NULL OR p_payment_method = 'cod' THEN
        INSERT INTO public.transactions(order_id, user_id, amount, payment_method, status, transaction_details)
        VALUES (new_order_id, auth_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);
    END IF;

    -- 4. Return the order number
    RETURN new_order_number;
END;
$$;

-- Function for admins to get detailed order information.
CREATE OR REPLACE FUNCTION public.get_admin_order_details(p_order_number text)
RETURNS TABLE (
    id integer,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    shipping_details jsonb,
    profiles jsonb,
    order_items jsonb,
    coupon_code text,
    discount_amount numeric,
    payment_method text,
    transaction_details jsonb
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details,
        jsonb_build_object(
            'full_name', p.full_name,
            'avatar_url', p.avatar_url
        ),
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', oi.id,
                    'quantity', oi.quantity,
                    'price_at_purchase', oi.price_at_purchase,
                    'products', jsonb_build_object(
                        'name', pr.name,
                        'featured_image_url', pr.featured_image_url
                    )
                )
            )
            FROM public.order_items oi
            JOIN public.products pr ON oi.product_id = pr.id
            WHERE oi.order_id = o.id
        ),
        o.coupon_code,
        o.discount_amount,
        o.payment_method,
        (SELECT t.transaction_details FROM public.transactions t WHERE t.order_id = o.id LIMIT 1)
    FROM
        public.orders o
    JOIN
        public.profiles p ON o.user_id = p.id
    WHERE
        o.order_number = p_order_number;
END;
$$;
