-- =================================================================
-- MASTER DATABASE SETUP SCRIPT
-- Version: 1.0
-- Description: Drops and recreates all custom types, functions,
--              and RLS policies to ensure a clean and correct state.
--              This script is designed to be run in its entirety.
-- =================================================================

-- Step 1: Drop existing objects in reverse order of dependency
-- =================================================================

-- Drop RLS policies that depend on functions
DROP POLICY IF EXISTS "Allow admin full access to settings" ON "public"."settings";
DROP POLICY IF EXISTS "Allow admin update" ON "public"."settings";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."settings";
DROP POLICY IF EXISTS "Allow admin delete for contact messages" ON "public"."contact_messages";
DROP POLICY IF EXISTS "Allow admin update for contact messages" ON "public"."contact_messages";
DROP POLICY IF EXISTS "Allow admin select for contact messages" ON "public"."contact_messages";
DROP POLICY IF EXISTS "Enable insert for all users" ON "public"."contact_messages";
DROP POLICY IF EXISTS "Allow admin full access" ON "public"."profiles";

-- Drop functions
DROP FUNCTION IF EXISTS "public"."is_admin"(user_id uuid);
DROP FUNCTION IF EXISTS "public"."get_my_role"();
DROP FUNCTION IF EXISTS "public"."create_order"(p_user_id uuid, p_total_amount numeric, p_shipping_details jsonb, p_items jsonb, p_payment_method text, p_transaction_details jsonb, p_coupon_code text, p_discount_amount numeric);
DROP FUNCTION IF EXISTS "public"."create_order"(p_user_id uuid, p_non_user_id bigint, p_total_amount numeric, p_shipping_details jsonb, p_items jsonb, p_payment_method text, p_transaction_details jsonb, p_coupon_code text, p_discount_amount numeric);
DROP FUNCTION IF EXISTS "public"."get_admin_orders"();

-- Drop types
DROP TYPE IF EXISTS "public"."cart_item";
DROP TYPE IF EXISTS "public"."shipping_details_type";


-- Step 2: Create Tables for Guest Checkout
-- =================================================================

-- Create a table for non-registered users
CREATE TABLE IF NOT EXISTS "public"."non_users" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" text NOT NULL,
    "shipping_details" jsonb,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "non_users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "non_users_email_key" UNIQUE ("email")
);
ALTER TABLE "public"."non_users" ENABLE ROW LEVEL SECURITY;


-- Step 3: Modify Existing Tables to support Guests
-- =================================================================

-- Add non_user_id to orders and make user_id nullable
ALTER TABLE "public"."orders" ADD COLUMN IF NOT EXISTS "non_user_id" bigint;
ALTER TABLE "public"."orders" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_non_user_id_fkey" FOREIGN KEY ("non_user_id") REFERENCES "public"."non_users"(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Add non_user_id to transactions and make user_id nullable
ALTER TABLE "public"."transactions" ADD COLUMN IF NOT EXISTS "non_user_id" bigint;
ALTER TABLE "public"."transactions" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "public"."transactions" ADD CONSTRAINT "transactions_non_user_id_fkey" FOREIGN KEY ("non_user_id") REFERENCES "public"."non_users"(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Ensure RLS is enabled on all relevant tables
ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


-- Step 4: Recreate Custom Types
-- =================================================================

CREATE TYPE "public"."cart_item" AS (
	"product_id" integer,
	"quantity" integer,
	"price" numeric
);

CREATE TYPE "public"."shipping_details_type" AS (
	"firstName" text,
	"lastName" text,
	"address" text,
	"city" text,
	"state" text,
	"zip" text,
	"email" text
);


-- Step 5: Recreate Functions
-- =================================================================

-- Function to check if a user is an admin
CREATE OR REPLACE FUNCTION "public"."is_admin"(user_id uuid)
RETURNS boolean
LANGUAGE "plpgsql" SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = user_id AND profiles.role IN ('admin', 'manager', 'super-admin')
  );
END;
$$;

-- Function for a user to get their own role securely
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TABLE(role text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT p.role
    FROM public.profiles p
    WHERE p.id = auth.uid();
END;
$$;

-- THE MAIN ORDER CREATION FUNCTION (Handles both registered and guest users)
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_non_user_id bigint,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    new_order_id bigint;
    new_order_number text;
    item record;
BEGIN
    -- Generate a unique order number
    new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || nextval('orders_id_seq');

    -- Insert the new order
    INSERT INTO public.orders (
        user_id, non_user_id, total_amount, shipping_details, order_number, 
        coupon_code, discount_amount, status
    )
    VALUES (
        p_user_id, p_non_user_id, p_total_amount, p_shipping_details, new_order_number,
        p_coupon_code, p_discount_amount, 'Pending'
    )
    RETURNING id INTO new_order_id;

    -- Insert order items
    FOR item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(product_id int, quantity int, price numeric)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (new_order_id, item.product_id, item.quantity, item.price);
    END LOOP;
    
    -- Insert transaction record
    INSERT INTO public.transactions(order_id, user_id, non_user_id, amount, payment_method, status, details)
    VALUES (new_order_id, p_user_id, p_non_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);

    RETURN new_order_number;
END;
$$;


-- Function to get orders for the admin dashboard (includes guests)
CREATE OR REPLACE FUNCTION public.get_admin_orders()
RETURNS TABLE(id bigint, user_id uuid, non_user_id bigint, order_number text, created_at timestamp with time zone, total_amount numeric, status public.order_status, customer_name text, customer_email text, customer_avatar_url text)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    o.id,
    o.user_id,
    o.non_user_id,
    o.order_number,
    o.created_at,
    o.total_amount,
    o.status,
    COALESCE(p.full_name, (o.shipping_details ->> 'firstName') || ' ' || (o.shipping_details ->> 'lastName'), 'Guest') AS customer_name,
    COALESCE(u.email, nu.email, o.shipping_details ->> 'email') AS customer_email,
    p.avatar_url AS customer_avatar_url
  FROM
    public.orders o
  LEFT JOIN
    public.profiles p ON o.user_id = p.id
  LEFT JOIN
    auth.users u ON o.user_id = u.id
  LEFT JOIN
    public.non_users nu ON o.non_user_id = nu.id
  ORDER BY
    o.created_at DESC;
END;
$$;


-- Step 6: Recreate RLS Policies
-- =================================================================

-- Settings Table Policies
CREATE POLICY "Enable read access for all users" ON "public"."settings"
AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Allow admin full access to settings" ON "public"."settings"
AS PERMISSIVE FOR ALL TO public
USING (is_admin(auth.uid()))
WITH CHECK (is_admin(auth.uid()));

-- Contact Messages Table Policies
CREATE POLICY "Enable insert for all users" ON "public"."contact_messages"
AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow admin select for contact messages" ON "public"."contact_messages"
AS PERMISSIVE FOR SELECT TO public USING (is_admin(auth.uid()));

CREATE POLICY "Allow admin update for contact messages" ON "public"."contact_messages"
AS PERMISSIVE FOR UPDATE TO public USING (is_admin(auth.uid()));

CREATE POLICY "Allow admin delete for contact messages" ON "public"."contact_messages"
AS PERMISSIVE FOR DELETE TO public USING (is_admin(auth.uid()));

-- Profiles Table Policies
CREATE POLICY "Allow admin full access" ON "public"."profiles"
AS PERMISSIVE FOR ALL TO public
USING (is_admin(auth.uid()))
WITH CHECK (is_admin(auth.uid()));

CREATE POLICY "Users can view their own profile" ON "public"."profiles"
AS PERMISSIVE FOR SELECT TO public
USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON "public"."profiles"
AS PERMISSIVE FOR UPDATE TO public
USING (auth.uid() = id);


-- =================================================================
-- END OF SCRIPT
-- =================================================================
