-- Drop the function first to avoid dependency issues.
DROP FUNCTION IF EXISTS public.create_new_order(numeric, jsonb, jsonb, text, jsonb, text, numeric, public.order_status, uuid);

-- Alter the table to ensure the 'id' column is a proper identity column.
-- This is the modern and correct way to do auto-incrementing keys in Postgres.
-- This will create and manage the sequence automatically.
-- We first drop any old, broken default that may exist from previous attempts.
ALTER TABLE public.orders ALTER COLUMN id DROP DEFAULT;

-- Then we add the IDENTITY property. This is the key fix.
-- This command is idempotent in spirit; if it's already an identity column
-- in some form, adding this ensures it's set correctly going forward.
ALTER TABLE public.orders
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- Now, recreate the function. It uses RETURNING id, which is the best practice
-- and will work now that the 'id' column is a proper identity column.
CREATE OR REPLACE FUNCTION create_new_order(
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric,
    p_initial_status public.order_status,
    p_user_id uuid
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_order_id int;
    new_order_number text;
BEGIN
    -- Insert the new order and get the generated ID
    INSERT INTO public.orders (
        user_id,
        total_amount,
        shipping_details,
        payment_method,
        payment_details,
        status,
        coupon_code,
        discount_amount
    )
    VALUES (
        p_user_id,
        p_total_amount,
        p_shipping_details,
        p_payment_method,
        p_transaction_details,
        p_initial_status,
        p_coupon_code,
        p_discount_amount
    )
    RETURNING id INTO new_order_id;

    -- Generate order number
    new_order_number := 'PB-' || to_char(CURRENT_DATE, 'YYMMDD') || '-' || new_order_id;

    -- Update the order with the generated order number
    UPDATE public.orders
    SET order_number = new_order_number
    WHERE id = new_order_id;

    -- Insert order items
    INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
    SELECT
        new_order_id,
        (item->>'product_id')::int,
        (item->>'quantity')::int,
        (item->>'price')::numeric
    FROM jsonb_array_elements(p_items) AS item;
    
    -- Insert into order history
    INSERT INTO public.order_history (order_id, status)
    VALUES (new_order_id, p_initial_status);

    RETURN new_order_number;
END;
$$;