-- =================================================================
-- MASTER DATABASE SETUP SCRIPT FOR PICKBAZAR
-- This script sets up tables, functions, and security policies.
-- Run this script in your Supabase SQL Editor.
-- =================================================================

-- Drop existing objects in reverse order of dependency to avoid errors.
-- Policies depend on functions, so drop policies first.
DROP POLICY IF EXISTS "Allow admin select for contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Allow admin update for contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Allow admin delete for contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Allow public insert for contact messages" ON public.contact_messages;

DROP POLICY IF EXISTS "Allow admin full access for settings" ON public.settings;

-- Now, functions can be dropped.
DROP FUNCTION IF EXISTS is_admin(user_id uuid);
DROP FUNCTION IF EXISTS get_all_users();
DROP FUNCTION IF EXISTS get_admin_reviews();
DROP FUNCTION IF EXISTS get_admin_refunds();
DROP FUNCTION IF EXISTS get_contact_messages();
DROP FUNCTION IF EXISTS get_contact_message_details(p_message_id BIGINT);
DROP FUNCTION IF EXISTS get_all_settings();

-- =================================================================
-- TABLES
-- =================================================================

-- Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Create contact_messages table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' NOT NULL, -- e.g., 'unread', 'read', 'archived'
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- =================================================================
-- HELPER FUNCTIONS & SECURITY
-- =================================================================

-- Create the is_admin function with SECURITY DEFINER
CREATE OR REPLACE FUNCTION is_admin(user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  -- Use SECURITY DEFINER to securely access the profiles table
  -- even within other RLS policies.
  SELECT role::text INTO user_role FROM public.profiles WHERE id = user_id;
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =================================================================

-- Enable RLS for settings table
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
-- Policy for settings: Allow admins full access.
CREATE POLICY "Allow admin full access for settings" ON public.settings
    FOR ALL
    USING (is_admin(auth.uid()))
    WITH CHECK (is_admin(auth.uid()));

-- Enable RLS for contact_messages table
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
-- Policy for contact_messages: Allow public insert.
CREATE POLICY "Allow public insert for contact messages" ON public.contact_messages
    FOR INSERT WITH CHECK (true);
-- Policy for contact_messages: Allow admins to select/view.
CREATE POLICY "Allow admin select for contact messages" ON public.contact_messages
    FOR SELECT USING (is_admin(auth.uid()));
-- Policy for contact_messages: Allow admins to update.
CREATE POLICY "Allow admin update for contact messages" ON public.contact_messages
    FOR UPDATE USING (is_admin(auth.uid()));
-- Policy for contact_messages: Allow admins to delete.
CREATE POLICY "Allow admin delete for contact messages" ON public.contact_messages
    FOR DELETE USING (is_admin(auth.uid()));


-- =================================================================
-- DATABASE FUNCTIONS (RPC)
-- =================================================================

-- Function to get all users for the admin user management page.
CREATE OR REPLACE FUNCTION get_all_users()
RETURNS TABLE (
    id UUID,
    full_name TEXT,
    email TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ,
    role TEXT
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        p.id,
        p.full_name,
        u.email,
        p.avatar_url,
        u.created_at,
        p.role::text
    FROM public.profiles p
    JOIN auth.users u ON p.id = u.id
    ORDER BY u.created_at DESC;
$$;


-- Function to get reviews for the admin reviews page.
CREATE OR REPLACE FUNCTION get_admin_reviews()
RETURNS TABLE (
    id BIGINT,
    rating INT,
    text TEXT,
    status TEXT,
    created_at TIMESTAMPTZ,
    author JSONB,
    product JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.id,
        r.rating,
        r.text,
        r.status::text,
        r.created_at,
        json_build_object(
            'name', p.full_name,
            'avatar_url', p.avatar_url
        ) AS author,
        json_build_object(
            'id', pr.id,
            'name', pr.name,
            'featured_image_url', pr.featured_image_url
        ) AS product
    FROM public.reviews r
    JOIN public.profiles p ON r.user_id = p.id
    JOIN public.products pr ON r.product_id = pr.id
    ORDER BY r.created_at DESC;
END;
$$;

-- Function to get refund requests for the admin refunds page.
CREATE OR REPLACE FUNCTION get_admin_refunds()
RETURNS TABLE(
    id bigint,
    order_id bigint,
    order_number text,
    amount real,
    status text,
    reason text,
    created_at timestamptz,
    user_id uuid,
    customer_name text,
    customer_avatar_url text
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    r.id,
    r.order_id,
    o.order_number,
    r.amount,
    r.status::text,
    r.reason,
    r.created_at,
    r.user_id,
    p.full_name as customer_name,
    p.avatar_url as customer_avatar_url
  FROM refunds r
  JOIN profiles p ON r.user_id = p.id
  JOIN orders o ON r.order_id = o.id
  ORDER BY r.created_at DESC;
END;
$$;

-- Function to securely get all contact messages for the admin page.
CREATE OR REPLACE FUNCTION get_contact_messages()
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Permission denied.';
    END IF;

    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date
    FROM public.contact_messages cm
    ORDER BY cm.created_at DESC;
END;
$$;

-- Function to get a single contact message's details.
CREATE OR REPLACE FUNCTION get_contact_message_details(p_message_id BIGINT)
RETURNS TABLE (
    id BIGINT,
    senderName TEXT,
    senderEmail TEXT,
    subject TEXT,
    message TEXT,
    status TEXT,
    date TIMESTAMPTZ,
    avatar JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Permission denied.';
    END IF;

    RETURN QUERY
    SELECT
        cm.id,
        cm.name as senderName,
        cm.email as senderEmail,
        cm.subject,
        cm.message,
        cm.status,
        cm.created_at as date,
        jsonb_build_object(
            'imageUrl', NULL,
            'imageHint', 'person icon'
        ) as avatar
    FROM public.contact_messages cm
    WHERE cm.id = p_message_id;
END;
$$;

-- Function to get all settings as a single JSON object.
CREATE OR REPLACE FUNCTION get_all_settings()
RETURNS json AS $$
DECLARE
    settings_json json;
BEGIN
    SELECT json_object_agg(key, value)
    INTO settings_json
    FROM public.settings;
    RETURN settings_json;
END;
$$ LANGUAGE plpgsql;