-- Drop existing functions to avoid conflicts, using CASCADE to handle dependencies.
DROP FUNCTION IF EXISTS is_admin(uuid);
DROP FUNCTION IF EXISTS get_admin_orders();
DROP FUNCTION IF EXISTS get_user_details(uuid);
DROP FUNCTION IF EXISTS get_admin_order_details(text);
DROP FUNCTION IF EXISTS get_admin_reviews();
DROP FUNCTION IF EXISTS get_admin_question_details(integer);
DROP FUNCTION IF EXISTS get_admin_questions();
DROP FUNCTION IF EXISTS get_admin_refunds();
DROP FUNCTION IF EXISTS get_admin_transactions();
DROP FUNCTION IF EXISTS get_all_users();
DROP FUNCTION IF EXISTS get_potential_admins();
DROP FUNCTION IF EXISTS get_category_tree();
DROP FUNCTION IF EXISTS get_contact_messages();
DROP FUNCTION IF EXISTS get_contact_message_details(integer);
DROP FUNCTION IF EXISTS get_my_role();
DROP FUNCTION IF EXISTS get_product_questions(integer);
DROP FUNCTION IF EXISTS get_product_rating_stats(integer);
DROP FUNCTION IF EXISTS get_product_reviews(integer);
DROP FUNCTION IF EXISTS get_related_products(integer, integer);
DROP FUNCTION IF EXISTS get_user_questions(uuid);
DROP FUNCTION IF EXISTS get_user_refunds(uuid);
DROP FUNCTION IF EXISTS get_user_reviews(uuid);
DROP FUNCTION IF EXISTS get_user_transactions(uuid);
DROP FUNCTION IF EXISTS update_home_sections(jsonb);
DROP FUNCTION IF EXISTS create_order(uuid,numeric,jsonb,jsonb,text,jsonb,text,numeric);


-- Drop tables if they exist
DROP TABLE IF EXISTS non_users CASCADE;


-- Create the non_users table to store guest information
CREATE TABLE non_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    shipping_details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add non_user_id columns to orders and transactions
ALTER TABLE orders ADD COLUMN IF NOT EXISTS non_user_id BIGINT REFERENCES non_users(id);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS non_user_id BIGINT REFERENCES non_users(id);

-- Make user_id nullable in orders and transactions to allow for guest orders
ALTER TABLE orders ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE transactions ALTER COLUMN user_id DROP NOT NULL;


-- Function to create an order for both registered users and guests
CREATE OR REPLACE FUNCTION create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text DEFAULT NULL,
    p_discount_amount numeric DEFAULT 0
)
RETURNS text AS $$
DECLARE
    v_order_id bigint;
    v_order_number text;
    v_non_user_id bigint;
    v_email text;
BEGIN
    -- Handle guest vs registered user
    IF p_user_id IS NULL THEN
        v_email := p_shipping_details->>'email';
        
        -- Find or create the non_user record
        SELECT id INTO v_non_user_id FROM non_users WHERE email = v_email;

        IF v_non_user_id IS NULL THEN
            INSERT INTO non_users (email, full_name, shipping_details)
            VALUES (
                v_email,
                p_shipping_details->>'firstName' || ' ' || p_shipping_details->>'lastName',
                p_shipping_details
            ) RETURNING id INTO v_non_user_id;
        END IF;

    END IF;

    -- Generate a unique order number
    v_order_number := 'ORD-' || to_char(NOW(), 'YYYYMMDD') || '-' || substr(md5(random()::text), 1, 6);

    -- Insert the order
    INSERT INTO orders (user_id, non_user_id, order_number, total_amount, shipping_details, coupon_code, discount_amount)
    VALUES (p_user_id, v_non_user_id, v_order_number, p_total_amount, p_shipping_details)
    RETURNING id INTO v_order_id;

    -- Insert order items
    INSERT INTO order_items (order_id, product_id, quantity, price_at_purchase)
    SELECT v_order_id, (item->>'product_id')::int, (item->>'quantity')::int, (item->>'price')::numeric
    FROM jsonb_array_elements(p_items) as item;

    -- Insert the transaction
    INSERT INTO transactions (order_id, user_id, non_user_id, amount, payment_method, status, details)
    VALUES (v_order_id, p_user_id, v_non_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);

    RETURN v_order_number;
END;
$$ LANGUAGE plpgsql;


-- Function to get admin orders, now including guest details
CREATE OR REPLACE FUNCTION get_admin_orders()
RETURNS TABLE(
    id bigint,
    user_id uuid,
    non_user_id bigint,
    order_number text,
    created_at timestamptz,
    total_amount numeric,
    status order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.user_id,
        o.non_user_id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, nu.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')) AS customer_name,
        COALESCE(u.email, nu.email, o.shipping_details->>'email') AS customer_email,
        p.avatar_url AS customer_avatar_url
    FROM
        orders o
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    LEFT JOIN
        profiles p ON o.user_id = p.id
    LEFT JOIN
        non_users nu ON o.non_user_id = nu.id
    ORDER BY
        o.created_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Helper function to check if a user is an admin or super-admin
CREATE OR REPLACE FUNCTION is_admin(p_user_id uuid)
RETURNS boolean AS $$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role INTO user_role FROM public.profiles WHERE id = p_user_id;
    RETURN user_role IN ('admin', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;