
-- =============================================
-- 1. NON-USERS TABLE
-- =============================================
-- Create a table to store basic information for guest users.
CREATE TABLE IF NOT EXISTS public.non_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.non_users ENABLE ROW LEVEL SECURITY;

-- =============================================
-- 2. ORDERS TABLE MODIFICATIONS
-- =============================================
-- Add a column to link orders to non_users.
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS non_user_id BIGINT REFERENCES public.non_users(id);

-- Make the user_id column nullable to allow for guest orders.
ALTER TABLE public.orders ALTER COLUMN user_id DROP NOT NULL;

-- =============================================
-- 3. TRANSACTIONS TABLE MODIFICATIONS
-- =============================================
-- Make the user_id column nullable for guest transactions.
ALTER TABLE public.transactions ALTER COLUMN user_id DROP NOT NULL;


-- =============================================
-- 4. CREATE_ORDER DATABASE FUNCTION
-- =============================================
-- Drop the existing function if it exists to avoid conflicts.
DROP FUNCTION IF EXISTS public.create_order(uuid,numeric,jsonb,jsonb,text,jsonb,text,numeric);

-- Create a new version of the function that handles both registered users and guests.
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb DEFAULT NULL,
    p_coupon_code text DEFAULT NULL,
    p_discount_amount numeric DEFAULT 0
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id bigint;
    v_order_number text;
    v_non_user_id bigint;
    item record;
BEGIN
    -- Handle guest vs. registered user
    IF p_user_id IS NULL THEN
        -- For guests, find or create a record in non_users table
        INSERT INTO public.non_users (email, name)
        VALUES (p_shipping_details->>'email', p_shipping_details->>'firstName' || ' ' || p_shipping_details->>'lastName')
        ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name
        RETURNING id INTO v_non_user_id;
    ELSE
        v_non_user_id := NULL;
    END IF;
    
    -- Generate a unique order number
    v_order_number := 'ORD-' || to_char(NOW(), 'YYMMDD') || '-' || LPAD(nextval('orders_id_seq')::text, 5, '0');

    -- Insert the order
    INSERT INTO public.orders (user_id, non_user_id, order_number, total_amount, shipping_details, coupon_code, discount_amount, status)
    VALUES (p_user_id, v_non_user_id, v_order_number, p_total_amount, p_shipping_details, p_coupon_code, p_discount_amount, 'Pending')
    RETURNING id INTO v_order_id;

    -- Insert order items
    FOR item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(product_id int, quantity int, price numeric)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (v_order_id, item.product_id, item.quantity, item.price);
    END LOOP;

    -- Insert transaction record
    INSERT INTO public.transactions (order_id, user_id, amount, payment_method, status, details)
    VALUES (v_order_id, p_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);

    RETURN v_order_number;
END;
$$;


-- =============================================
-- 5. GET_ADMIN_ORDERS DATABASE FUNCTION
-- =============================================
-- This function fetches all orders for the admin dashboard, combining user and non-user data.
CREATE OR REPLACE FUNCTION public.get_admin_orders()
RETURNS TABLE (
    id bigint,
    user_id uuid,
    non_user_id bigint,
    order_number text,
    created_at timestamptz,
    total_amount numeric,
    status public.order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.user_id,
        o.non_user_id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, nu.name, o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName') AS customer_name,
        COALESCE(u.email, nu.email, o.shipping_details->>'email') AS customer_email,
        p.avatar_url AS customer_avatar_url
    FROM
        public.orders o
    LEFT JOIN
        public.profiles p ON o.user_id = p.id
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    LEFT JOIN
        public.non_users nu ON o.non_user_id = nu.id
    ORDER BY
        o.created_at DESC;
END;
$$;


-- =============================================
-- 6. GET_ADMIN_ORDER_DETAILS DATABASE FUNCTION
-- =============================================
-- This function fetches detailed information for a single order, handling both user types.
CREATE OR REPLACE FUNCTION public.get_admin_order_details(p_order_number text)
RETURNS TABLE (
    id bigint,
    order_number text,
    created_at timestamptz,
    total_amount numeric,
    status public.order_status,
    shipping_details jsonb,
    profiles jsonb,
    order_items jsonb,
    coupon_code text,
    discount_amount numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details,
        COALESCE(
            (SELECT jsonb_build_object('full_name', p.full_name, 'avatar_url', p.avatar_url)
             FROM public.profiles p WHERE p.id = o.user_id),
            (SELECT jsonb_build_object('full_name', nu.name, 'avatar_url', null)
             FROM public.non_users nu WHERE nu.id = o.non_user_id),
            jsonb_build_object('full_name', o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName', 'avatar_url', null)
        ) AS profiles,
        (SELECT jsonb_agg(
            jsonb_build_object(
                'id', oi.id,
                'quantity', oi.quantity,
                'price_at_purchase', oi.price_at_purchase,
                'products', jsonb_build_object(
                    'name', pr.name,
                    'featured_image_url', pr.featured_image_url
                )
            )
        ) FROM public.order_items oi JOIN public.products pr ON oi.product_id = pr.id WHERE oi.order_id = o.id) AS order_items,
        o.coupon_code,
        o.discount_amount
    FROM public.orders o
    WHERE o.order_number = p_order_number;
END;
$$;

    