-- Create enum type for notification types if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN
        CREATE TYPE public.notification_type AS ENUM (
            'new_order'
        );
    END IF;
END$$;


-- Create notifications table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, -- For user-specific notifications, NULL for admin
    title text NOT NULL,
    message text,
    link text,
    is_read boolean DEFAULT false,
    type public.notification_type,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Function to create a notification on a new order
CREATE OR REPLACE FUNCTION public.handle_new_order_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.notifications (title, message, link, type)
    VALUES (
        'New Order Received',
        'Order ' || NEW.order_number || ' has been placed for $' || NEW.total_amount,
        '/admin/orders/' || NEW.order_number,
        'new_order'
    );
    RETURN NEW;
END;
$$;

-- Drop existing trigger to avoid duplication, then create it
DROP TRIGGER IF EXISTS on_new_order_notification ON public.orders;
CREATE TRIGGER on_new_order_notification
AFTER INSERT ON public.orders
FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_order_notification();


-- RPC function for admins to get notifications
CREATE OR REPLACE FUNCTION get_admin_notifications()
RETURNS TABLE (
    id bigint,
    title text,
    message text,
    link text,
    is_read boolean,
    created_at timestamp with time zone,
    type notification_type
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        n.id,
        n.title,
        n.message,
        n.link,
        n.is_read,
        n.created_at,
        n.type
    FROM
        public.notifications n
    WHERE
        n.user_id IS NULL -- Admin notifications don't have a user_id
    ORDER BY
        n.created_at DESC;
END;
$$;

-- Enable RLS on the table if not already enabled
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Drop policies before creating them to avoid errors on re-run
DROP POLICY IF EXISTS "Allow admin read access to notifications" ON public.notifications;
DROP POLICY IF EXISTS "Allow admin update access to notifications" ON public.notifications;

-- We assume an is_admin() function exists based on previous files.
CREATE POLICY "Allow admin read access to notifications"
ON public.notifications
FOR SELECT
TO authenticated
USING (is_admin(auth.uid()));

CREATE POLICY "Allow admin update access to notifications"
ON public.notifications
FOR UPDATE
TO authenticated
USING (is_admin(auth.uid()));
