-- =================================================================
-- COMPLETE RESET FOR ORDERS AND NOTIFICATIONS
-- This script will drop and recreate all related tables, types, and functions.
-- =================================================================

-- Step 1: Drop existing objects with CASCADE to resolve dependencies and ambiguity
DROP FUNCTION IF EXISTS public.create_order(uuid,numeric,jsonb,jsonb,text,jsonb,text,numeric);
DROP FUNCTION IF EXISTS public.create_order(uuid,numeric,jsonb,jsonb[],text,jsonb,text,numeric);
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, jsonb, text, jsonb);
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, jsonb, text, jsonb, text, numeric, text);

DROP FUNCTION IF EXISTS public.get_admin_order_list();
DROP FUNCTION IF EXISTS public.get_admin_order_details(p_order_number text);
DROP FUNCTION IF EXISTS public.get_admin_transactions();
DROP FUNCTION IF EXISTS public.get_admin_notifications();
DROP FUNCTION IF EXISTS public.create_notification(text,text,text,uuid,user_role);

DROP TYPE IF EXISTS public.order_status CASCADE;
DROP TYPE IF EXISTS public.notification_type CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;

-- Step 2: Recreate all necessary types
CREATE TYPE public.order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
CREATE TYPE public.notification_type AS ENUM ('new_order', 'new_review', 'new_question', 'new_message', 'order_status_update', 'refund_request');
CREATE TYPE public.user_role AS ENUM ('admin', 'manager', 'super-admin');

-- Step 3: Recreate the 'orders' table to ensure correct schema
DROP TABLE IF EXISTS public.orders CASCADE;
CREATE TABLE public.orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    total_amount numeric(10,2) NOT NULL,
    status public.order_status NOT NULL DEFAULT 'Pending'::public.order_status,
    shipping_details jsonb,
    order_number text NOT NULL,
    coupon_code text,
    discount_amount numeric(10,2),
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_number_key UNIQUE (order_number)
);
-- Add foreign key back to profiles if it exists
ALTER TABLE public.orders
ADD CONSTRAINT orders_user_id_fkey
FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;


-- Step 4: Recreate the 'notifications' table
DROP TABLE IF EXISTS public.notifications;
CREATE TABLE public.notifications (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    recipient_user_id uuid,
    recipient_role user_role,
    title text NOT NULL,
    message text,
    link text,
    is_read boolean NOT NULL DEFAULT false,
    type notification_type,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);


-- Step 5: Recreate the SINGLE, CORRECT 'create_order' function
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_order_id bigint;
    new_order_number text;
    new_transaction_id bigint;
    order_item jsonb;
BEGIN
    -- Generate a unique order number
    new_order_number := 'PB-' || to_char(now(), 'YYMMDD') || '-' || nextval('orders_id_seq');

    -- Insert the order
    INSERT INTO public.orders (user_id, total_amount, shipping_details, status, order_number, coupon_code, discount_amount)
    VALUES (p_user_id, p_total_amount, p_shipping_details, 'Pending', new_order_number, p_coupon_code, p_discount_amount)
    RETURNING id INTO new_order_id;

    -- Insert order items
    FOR order_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (
            new_order_id,
            (order_item->>'product_id')::bigint,
            (order_item->>'quantity')::integer,
            (order_item->>'price')::numeric
        );
    END LOOP;

    -- Insert transaction
    INSERT INTO public.transactions (order_id, user_id, amount, payment_method, status, transaction_details)
    VALUES (new_order_id, p_user_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details)
    RETURNING id into new_transaction_id;

    -- Create notification for admins
    INSERT INTO public.notifications (recipient_role, title, message, link, type)
    VALUES 
        ('admin'::public.user_role, 'New Order Received', 'A new order ' || new_order_number || ' has been placed.', '/admin/orders/' || new_order_number, 'new_order'),
        ('manager'::public.user_role, 'New Order Received', 'A new order ' || new_order_number || ' has been placed.', '/admin/orders/' || new_order_number, 'new_order');

    RETURN new_order_number;
END;
$$;


-- Step 6: Recreate other necessary functions to prevent future errors

CREATE OR REPLACE FUNCTION public.get_admin_order_list()
RETURNS TABLE(
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName'))::text AS customer_name,
        COALESCE(u.email, o.shipping_details->>'email')::text AS customer_email,
        p.avatar_url::text AS customer_avatar_url
    FROM
        public.orders o
    LEFT JOIN
        public.profiles p ON o.user_id = p.id
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    ORDER BY
        o.created_at DESC;
$$;


CREATE OR REPLACE FUNCTION public.get_admin_transactions()
RETURNS TABLE(
    id bigint,
    order_id bigint,
    order_number text,
    customer_name text,
    customer_avatar text,
    amount numeric,
    payment_method text,
    status text,
    created_at timestamp with time zone
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    t.id,
    t.order_id,
    o.order_number,
    COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName'))::text as customer_name,
    p.avatar_url::text as customer_avatar,
    t.amount,
    t.payment_method,
    t.status,
    t.created_at
  FROM public.transactions t
  LEFT JOIN public.orders o ON t.order_id = o.id
  LEFT JOIN public.profiles p ON t.user_id = p.id
  ORDER BY t.created_at DESC;
$$;


CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS TABLE(
    id bigint,
    title text,
    message text,
    link text,
    is_read boolean,
    created_at timestamp with time zone,
    type notification_type
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id, title, message, link, is_read, created_at, type
  FROM public.notifications
  WHERE recipient_role IN ('admin', 'manager', 'super-admin')
  ORDER BY created_at DESC;
$$;

-- Grant usage on the sequence to the authenticated role
GRANT USAGE, SELECT ON SEQUENCE public.orders_id_seq TO authenticated;
