-- Drop existing objects in the correct order to avoid dependency issues.
DROP TRIGGER IF EXISTS on_new_order ON public.orders;
DROP FUNCTION IF EXISTS public.handle_new_order();
DROP FUNCTION IF EXISTS public.get_admin_notifications();
DROP TABLE IF EXISTS public.notifications;
DROP TYPE IF EXISTS public.notification_type;

-- Create a type for different notification categories.
CREATE TYPE public.notification_type AS ENUM (
    'new_order',
    'new_review',
    'new_question',
    'refund_request',
    'contact_message'
);

-- Create the notifications table.
-- user_id is for notifications specific to a user (e.g., order shipped).
-- A NULL user_id indicates a system-wide notification for admins.
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    title text NOT NULL,
    message text,
    link text,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type notification_type
);

-- Add comments for clarity
COMMENT ON TABLE public.notifications IS 'Stores notifications for users and admins.';
COMMENT ON COLUMN public.notifications.user_id IS 'NULL for admin-only system notifications.';

-- Enable Row Level Security
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Create the function that will be called by the trigger.
-- This function inserts a row into the notifications table for admins.
CREATE OR REPLACE FUNCTION public.handle_new_order()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notifications (title, message, link, type)
  VALUES (
    'New Order Received',
    'Order #' || NEW.order_number || ' for $' || NEW.total_amount::text || ' has been placed.',
    '/admin/orders/' || NEW.order_number,
    'new_order'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the trigger that fires after a new order is inserted.
CREATE TRIGGER on_new_order
  AFTER INSERT ON public.orders
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_order();

-- Create a function for the app to fetch admin notifications.
CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS TABLE(
    id bigint,
    title text,
    message text,
    link text,
    is_read boolean,
    created_at timestamp with time zone,
    type text
) AS $$
BEGIN
    -- RLS policies will ensure only authorized roles can access this.
    RETURN QUERY
    SELECT
        n.id,
        n.title,
        n.message,
        n.link,
        n.is_read,
        n.created_at,
        n.type::text
    FROM
        public.notifications n
    WHERE 
        n.user_id IS NULL -- Select system-wide notifications for admins
    ORDER BY
        n.created_at DESC;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- RLS Policies for the notifications table

-- Allow admin roles to see system-wide notifications (where user_id is NULL)
CREATE POLICY "Allow admin read access to system notifications"
ON public.notifications
FOR SELECT
TO authenticated
USING (
    (get_my_role() IN ('admin', 'manager', 'super-admin')) AND (user_id IS NULL)
);

-- Allow admins to update the is_read status of notifications
CREATE POLICY "Allow admin update of notifications"
ON public.notifications
FOR UPDATE
TO authenticated
USING (
    get_my_role() IN ('admin', 'manager', 'super-admin')
)
WITH CHECK (
    get_my_role() IN ('admin', 'manager', 'super-admin')
);
