-- Drop existing objects in reverse order of dependency, using CASCADE
DROP FUNCTION IF EXISTS public.get_admin_order_list();
DROP FUNCTION IF EXISTS public.create_order(uuid, numeric, jsonb, jsonb[], text, jsonb, text, numeric);
DROP FUNCTION IF EXISTS public.get_admin_order_details(p_order_number text);
DROP FUNCTION IF EXISTS public.get_admin_transactions();
DROP FUNCTION IF EXISTS public.get_admin_notifications();


-- Drop tables using CASCADE
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;


-- Drop types using CASCADE
DROP TYPE IF EXISTS public.order_status CASCADE;
DROP TYPE IF EXISTS public.notification_type CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;


-- Recreate types
CREATE TYPE public.order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
CREATE TYPE public.notification_type AS ENUM ('new_order', 'new_review', 'status_change');
CREATE TYPE public.user_role AS ENUM ('customer', 'manager', 'admin', 'super-admin');


-- Recreate tables
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    status public.order_status DEFAULT 'Pending'::public.order_status NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    shipping_details jsonb,
    order_number text UNIQUE NOT NULL,
    coupon_code text,
    discount_amount numeric(10,2)
);

CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
    quantity integer NOT NULL,
    price_at_purchase numeric(10, 2) NOT NULL
);

CREATE TABLE public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_method text,
    status text,
    transaction_details jsonb
);

CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    title text NOT NULL,
    message text,
    link text,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    recipient_role public.user_role,
    type public.notification_type
);

-- Recreate functions

-- Function to create an order
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb[],
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_order_id bigint;
    new_order_number text;
    item jsonb;
BEGIN
    -- Generate a unique order number
    new_order_number := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || nextval('orders_id_seq');

    -- Insert the order
    INSERT INTO public.orders (user_id, total_amount, shipping_details, order_number, coupon_code, discount_amount, status)
    VALUES (p_user_id, p_total_amount, p_shipping_details, new_order_number, p_coupon_code, p_discount_amount, 'Pending')
    RETURNING id INTO new_order_id;

    -- Insert order items
    FOREACH item IN ARRAY p_items
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (new_order_id, (item->>'product_id')::bigint, (item->>'quantity')::int, (item->>'price')::numeric);
    END LOOP;
    
    -- Insert transaction
    INSERT INTO public.transactions(order_id, amount, payment_method, status, transaction_details)
    VALUES (new_order_id, p_total_amount, p_payment_method, 'Completed', p_transaction_details);

    -- Insert notification for admins
    INSERT INTO public.notifications (title, message, link, recipient_role, type)
    VALUES ('New Order Received', 'A new order ' || new_order_number || ' has been placed.', '/admin/orders/' || new_order_number, 'admin', 'new_order');

    RETURN new_order_number;
END;
$$;


-- Function for the admin orders page
CREATE OR REPLACE FUNCTION public.get_admin_order_list()
RETURNS TABLE(
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')) AS customer_name,
        COALESCE(u.email, o.shipping_details->>'email') AS customer_email,
        p.avatar_url AS customer_avatar_url
    FROM
        public.orders o
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    LEFT JOIN
        public.profiles p ON o.user_id = p.id
    ORDER BY
        o.created_at DESC;
$$;


-- Function for the admin order details page
CREATE OR REPLACE FUNCTION public.get_admin_order_details(p_order_number text)
RETURNS TABLE (
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    shipping_details jsonb,
    profiles jsonb,
    order_items jsonb,
    coupon_code text,
    discount_amount numeric,
    payment_method text,
    transaction_details jsonb
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        o.shipping_details,
        jsonb_build_object(
            'full_name', COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')),
            'avatar_url', p.avatar_url
        ) as profiles,
        (SELECT jsonb_agg(jsonb_build_object(
            'id', oi.id,
            'quantity', oi.quantity,
            'price_at_purchase', oi.price_at_purchase,
            'products', jsonb_build_object(
                'name', pr.name,
                'featured_image_url', pr.featured_image_url
            )
        )) FROM public.order_items oi JOIN public.products pr ON oi.product_id = pr.id WHERE oi.order_id = o.id) as order_items,
        o.coupon_code,
        o.discount_amount,
        t.payment_method,
        t.transaction_details
    FROM
        public.orders o
    LEFT JOIN public.profiles p ON o.user_id = p.id
    LEFT JOIN public.transactions t ON o.id = t.order_id
    WHERE o.order_number = p_order_number;
$$;

-- Function to get notifications for admins
CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS TABLE (
    id bigint,
    title text,
    message text,
    link text,
    is_read boolean,
    created_at timestamp with time zone,
    type public.notification_type
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        id,
        title,
        message,
        link,
        is_read,
        created_at,
        type
    FROM public.notifications
    WHERE recipient_role = 'admin' OR recipient_role IS NULL
    ORDER BY created_at DESC
    LIMIT 20;
$$;

-- Function to get admin transactions
CREATE OR REPLACE FUNCTION public.get_admin_transactions()
RETURNS TABLE(
    id bigint,
    order_id bigint,
    order_number text,
    customer_name text,
    customer_avatar text,
    amount numeric,
    payment_method text,
    status text,
    created_at timestamp with time zone
)
LANGUAGE sql
SECURITY DEFINER
AS $$
SELECT
    t.id,
    t.order_id,
    o.order_number,
    COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')) AS customer_name,
    p.avatar_url as customer_avatar,
    t.amount,
    t.payment_method,
    t.status,
    t.created_at
FROM public.transactions t
JOIN public.orders o ON t.order_id = o.id
LEFT JOIN public.profiles p ON o.user_id = p.id
ORDER BY t.created_at DESC;
$$;

-- Grant usage on the new sequences to the authenticated role
GRANT USAGE, SELECT ON SEQUENCE public.orders_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.order_items_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.transactions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.notifications_id_seq TO authenticated;

-- Grant permissions on tables
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.orders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.order_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.notifications TO authenticated;

-- Grant execute on functions
GRANT EXECUTE ON FUNCTION public.create_order(uuid, numeric, jsonb, jsonb[], text, jsonb, text, numeric) TO authenticated;

-- For anon role (if needed for certain public functions, though likely not for these)
GRANT USAGE, SELECT ON SEQUENCE public.orders_id_seq TO anon;