-- =================================================================
-- Complete, Targeted Reset for Orders and Notifications Schema
-- =================================================================
-- This script will forcefully drop and recreate all objects related
-- to orders and notifications to ensure a clean and correct state.

-- Step 1: Forcefully drop all related objects using CASCADE to resolve dependency errors.
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TYPE IF EXISTS public.order_status CASCADE;
DROP TYPE IF EXISTS public.notification_type CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;

-- Step 2: Re-create the custom data types.
CREATE TYPE public.order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
CREATE TYPE public.notification_type AS ENUM ('new_order', 'order_shipped', 'new_review', 'new_question', 'refund_request');
CREATE TYPE public.user_role AS ENUM ('customer', 'manager', 'admin', 'super-admin');

-- Step 3: Re-create the tables with the correct schema.
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    order_number text NOT NULL UNIQUE DEFAULT 'ORD-' || substr(md5(random()::text), 0, 10),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    status public.order_status DEFAULT 'Pending' NOT NULL,
    shipping_details jsonb NOT NULL,
    coupon_code text,
    discount_amount numeric(10, 2)
);

CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES public.products(id),
    quantity integer NOT NULL,
    price_at_purchase numeric(10, 2) NOT NULL
);

CREATE TABLE public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_method text NOT NULL,
    status text DEFAULT 'Completed' NOT NULL, -- e.g., 'Completed', 'Failed'
    transaction_details jsonb
);

CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    recipient_role user_role, -- e.g. for notifying all 'admin's
    title text NOT NULL,
    message text,
    link text,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type notification_type
);

-- Step 4: Re-create all necessary functions with corrected logic.

-- Function to create an order
CREATE OR REPLACE FUNCTION public.create_order(
    p_user_id uuid,
    p_total_amount numeric,
    p_shipping_details jsonb,
    p_items jsonb,
    p_payment_method text,
    p_transaction_details jsonb,
    p_coupon_code text,
    p_discount_amount numeric
)
RETURNS text -- Returns the order_number
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_order_id bigint;
    new_order_number text;
    item record;
BEGIN
    -- Insert into orders table and get the new order's ID and number
    INSERT INTO public.orders (user_id, total_amount, status, shipping_details, coupon_code, discount_amount)
    VALUES (p_user_id, p_total_amount, 'Pending', p_shipping_details, p_coupon_code, p_discount_amount)
    RETURNING id, order_number INTO new_order_id, new_order_number;

    -- Insert order items
    FOR item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(product_id int, quantity int, price numeric)
    LOOP
        INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
        VALUES (new_order_id, item.product_id, item.quantity, item.price);
    END LOOP;

    -- Insert transaction record
    INSERT INTO public.transactions(order_id, amount, payment_method, transaction_details)
    VALUES (new_order_id, p_total_amount, p_payment_method, p_transaction_details);

    -- Create notification for admins
    INSERT INTO public.notifications(recipient_role, title, message, link, type)
    VALUES ('admin', 'New Order Received', 'A new order ' || new_order_number || ' has been placed.', '/admin/orders/' || new_order_number, 'new_order');

    RETURN new_order_number;
END;
$$;


-- Function for admin to list orders
CREATE OR REPLACE FUNCTION public.get_admin_order_list()
RETURNS TABLE(
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    customer_name text,
    customer_email text,
    customer_avatar_url text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
    SELECT
        o.id,
        o.order_number,
        o.created_at,
        o.total_amount,
        o.status,
        COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')) AS customer_name,
        COALESCE(u.email, o.shipping_details->>'email') AS customer_email,
        p.avatar_url AS customer_avatar_url
    FROM
        public.orders o
    LEFT JOIN
        public.profiles p ON o.user_id = p.id
    LEFT JOIN
        auth.users u ON o.user_id = u.id
    ORDER BY
        o.created_at DESC;
$$;


-- Function to get admin order details
CREATE OR REPLACE FUNCTION public.get_admin_order_details(p_order_number text)
RETURNS TABLE (
    id bigint,
    order_number text,
    created_at timestamp with time zone,
    total_amount numeric,
    status public.order_status,
    shipping_details jsonb,
    profiles jsonb,
    order_items jsonb,
    coupon_code text,
    discount_amount numeric,
    payment_method text,
    transaction_details jsonb
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
SELECT
    o.id,
    o.order_number,
    o.created_at,
    o.total_amount,
    o.status,
    o.shipping_details,
    jsonb_build_object(
        'full_name', COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')),
        'avatar_url', p.avatar_url
    ) AS profiles,
    (SELECT jsonb_agg(
        jsonb_build_object(
            'id', oi.id,
            'quantity', oi.quantity,
            'price_at_purchase', oi.price_at_purchase,
            'products', jsonb_build_object(
                'name', pr.name,
                'featured_image_url', pr.featured_image_url
            )
        )
    ) FROM public.order_items oi JOIN public.products pr ON oi.product_id = pr.id WHERE oi.order_id = o.id) AS order_items,
    o.coupon_code,
    o.discount_amount,
    t.payment_method,
    t.transaction_details
FROM public.orders o
LEFT JOIN public.profiles p ON o.user_id = p.id
LEFT JOIN public.transactions t ON o.id = t.order_id
WHERE o.order_number = p_order_number;
$$;


-- Function to get admin notifications
CREATE OR REPLACE FUNCTION public.get_admin_notifications()
RETURNS TABLE (
    id bigint,
    title text,
    message text,
    link text,
    is_read boolean,
    created_at timestamp with time zone,
    type notification_type
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
    SELECT id, title, message, link, is_read, created_at, type
    FROM public.notifications
    WHERE recipient_role = 'admin'
    ORDER BY created_at DESC;
$$;


-- Function to get admin transactions
CREATE OR REPLACE FUNCTION public.get_admin_transactions()
RETURNS TABLE (
    id bigint,
    order_id bigint,
    order_number text,
    customer_name text,
    customer_avatar text,
    amount numeric,
    payment_method text,
    status text,
    created_at timestamp with time zone
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
    SELECT
        t.id,
        t.order_id,
        o.order_number,
        COALESCE(p.full_name, (o.shipping_details->>'firstName' || ' ' || o.shipping_details->>'lastName')) AS customer_name,
        p.avatar_url AS customer_avatar,
        t.amount,
        t.payment_method,
        t.status,
        t.created_at
    FROM public.transactions t
    JOIN public.orders o ON t.order_id = o.id
    LEFT JOIN public.profiles p ON o.user_id = p.id
    ORDER BY t.created_at DESC;
$$;


-- Step 5: Set up Row Level Security (RLS) policies.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage all orders" ON public.orders FOR ALL USING (public.get_my_role() IN ('admin', 'super-admin', 'manager'));
CREATE POLICY "Users can view items of their own orders" ON public.order_items FOR SELECT USING ((SELECT user_id FROM public.orders WHERE id = order_id) = auth.uid());
CREATE POLICY "Admins can view all order items" ON public.order_items FOR SELECT USING (public.get_my_role() IN ('admin', 'super-admin', 'manager'));
CREATE POLICY "Users can view their own transactions" ON public.transactions FOR SELECT USING ((SELECT user_id FROM public.orders WHERE id = order_id) = auth.uid());
CREATE POLICY "Admins can view all transactions" ON public.transactions FOR SELECT USING (public.get_my_role() IN ('admin', 'super-admin', 'manager'));
CREATE POLICY "Users can view their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view admin notifications" ON public.notifications FOR SELECT USING (recipient_role = 'admin');

-- Step 6: Grant permissions for the new schema.
GRANT USAGE ON TYPE public.order_status TO anon, authenticated, service_role;
GRANT USAGE ON TYPE public.notification_type TO anon, authenticated, service_role;
GRANT USAGE ON TYPE public.user_role TO anon, authenticated, service_role;

GRANT ALL ON TABLE public.orders TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.order_items TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.transactions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.notifications TO anon, authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.create_order(uuid,numeric,jsonb,jsonb,text,jsonb,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_order_list() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_order_details(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_notifications() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_transactions() TO authenticated;
