
-- 1. Create the refunds table
CREATE TABLE IF NOT EXISTS refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reason TEXT,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Trigger to update the updated_at timestamp on any change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_refunds_updated_at ON refunds;
CREATE TRIGGER update_refunds_updated_at
BEFORE UPDATE ON refunds
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();


-- 3. Enable Row Level Security (RLS) on the new table
ALTER TABLE refunds ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for the refunds table
DROP POLICY IF EXISTS "Users can view their own refunds" ON refunds;
CREATE POLICY "Users can view their own refunds" ON refunds
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own refunds" ON refunds;
CREATE POLICY "Users can insert their own refunds" ON refunds
FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins have full access on refunds" ON refunds;
CREATE POLICY "Admins have full access on refunds" ON refunds
FOR ALL USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'manager', 'super-admin')
);

DROP POLICY IF EXISTS "Users can delete their own pending refunds" ON refunds;
CREATE POLICY "Users can delete their own pending refunds" ON refunds
FOR DELETE USING (auth.uid() = user_id AND status = 'Pending');


-- 5. Create a function for users to get their refund history
CREATE OR REPLACE FUNCTION get_user_refunds(p_user_id UUID)
RETURNS TABLE (
    id BIGINT,
    order_id BIGINT,
    order_number TEXT,
    amount NUMERIC,
    status TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.id,
        r.order_id,
        o.order_number,
        r.amount,
        r.status,
        r.reason,
        r.created_at
    FROM refunds r
    JOIN orders o ON r.order_id = o.id
    WHERE r.user_id = p_user_id
    ORDER BY r.created_at DESC;
END;
$$;

-- 6. Create a function for admins to get all refund requests
CREATE OR REPLACE FUNCTION get_admin_refunds()
RETURNS TABLE (
    id BIGINT,
    order_id BIGINT,
    order_number TEXT,
    amount NUMERIC,
    status TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ,
    user_id UUID,
    customer_name TEXT,
    customer_avatar_url TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.id,
        r.order_id,
        o.order_number,
        r.amount,
        r.status,
        r.reason,
        r.created_at,
        r.user_id,
        p.full_name AS customer_name,
        p.avatar_url AS customer_avatar_url
    FROM refunds r
    JOIN orders o ON r.order_id = o.id
    JOIN profiles p ON r.user_id = p.id
    ORDER BY r.created_at DESC;
END;
$$;
