-- This function securely checks if a user is an admin, manager, or super-admin.
-- It is defined with SECURITY DEFINER to run with the permissions of the user who defined it,
-- allowing it to safely access the 'profiles' table.
CREATE OR REPLACE FUNCTION is_admin(user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  -- We select the role from the public.profiles table for the given user_id.
  -- This is a safe operation because the function is SECURITY DEFINER.
  SELECT role::text INTO user_role FROM public.profiles WHERE id = user_id;

  -- The function returns true if the user's role is one of the administrative roles.
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 1. Create the settings table if it doesn't already exist.
-- This table uses a simple key-value structure to store site-wide settings.
-- The "key" column is unique to prevent duplicate settings.
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key TEXT NOT NULL UNIQUE,
    value TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Enable Row Level Security (RLS) on the settings table.
-- This is a crucial security step that ensures no one can access the table
-- unless a specific policy allows them to.
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;


-- 3. Define RLS Policies for the settings table.
-- These policies control who can do what with the data.

-- Drop existing policies to ensure a clean state before creating new ones.
DROP POLICY IF EXISTS "Allow public read access to all settings" ON public.settings;
DROP POLICY IF EXISTS "Allow admin full access to settings" ON public.settings;


-- POLICY: Allow anyone to read the settings.
-- This is necessary so that the frontend application can display things like the site title and logo.
CREATE POLICY "Allow public read access to all settings" ON public.settings
    FOR SELECT USING (true);

-- POLICY: Allow admin users (admin, manager, super-admin) to do anything.
-- This policy uses the is_admin() helper function to securely check the user's role.
CREATE POLICY "Allow admin full access to settings" ON public.settings
    FOR ALL USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));


-- 4. Create a function to securely fetch all settings as a single JSON object.
-- This is more efficient for the frontend than fetching each setting individually.
CREATE OR REPLACE FUNCTION get_all_settings()
RETURNS jsonb
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN (SELECT jsonb_object_agg(key, value) FROM public.settings);
END;
$$;
