-- This script sets up a key-value table for general site settings
-- and provides a secure way for admins to manage them.

-- Helper function to check if a user is an admin or higher.
-- This function is used to secure other parts of the database.
CREATE OR REPLACE FUNCTION is_admin(user_id uuid)
RETURNS boolean AS $$
DECLARE
  user_role TEXT;
BEGIN
  -- Select the role into a variable, converting it to text
  SELECT role::text INTO user_role FROM public.profiles WHERE id = user_id;
  -- Check if the user's role is one of the administrative roles
  RETURN user_role IN ('admin', 'manager', 'super-admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 1. Creates a table to store general application settings
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 3. Define Policies for the settings table
DROP POLICY IF EXISTS "Allow public read for all settings" ON public.settings;
CREATE POLICY "Allow public read for all settings" ON public.settings
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin update for settings" ON public.settings;
CREATE POLICY "Allow admin update for settings" ON public.settings
    FOR UPDATE USING (is_admin(auth.uid()));

-- 4. Pre-populate with default settings
INSERT INTO public.settings (key, value) VALUES
    ('site_title', 'Pickbazar'),
    ('site_subtitle', 'Your friendly neighborhood grocery store'),
    ('logo_url', NULL),
    ('favicon_url', NULL),
    ('link_preview_image_url', NULL)
ON CONFLICT (key) DO NOTHING;

-- 5. Function to get all settings as a single JSON object for easy client-side fetching
CREATE OR REPLACE FUNCTION get_all_settings()
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    settings_json JSONB;
BEGIN
    SELECT jsonb_object_agg(key, value)
    INTO settings_json
    FROM public.settings;
    
    RETURN settings_json;
END;
$$;

-- 6. Create a trigger to automatically update the 'updated_at' column on any change
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_settings_update ON public.settings;
CREATE TRIGGER on_settings_update
BEFORE UPDATE ON public.settings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
