-- Drop existing objects to start fresh.
-- This makes the script idempotent (safe to run multiple times).

-- Drop trigger and function
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Drop addresses table and its policies
DROP POLICY IF EXISTS "Users can delete their own addresses." ON public.addresses;
DROP POLICY IF EXISTS "Users can update their own addresses." ON public.addresses;
DROP POLICY IF EXISTS "Users can insert their own addresses." ON public.addresses;
DROP POLICY IF EXISTS "Users can view their own addresses." ON public.addresses;
DROP TABLE IF EXISTS public.addresses;

-- Drop profiles table and its policies
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP TABLE IF EXISTS public.profiles;

-- Drop storage policies
DROP POLICY IF EXISTS "Anyone can update their own avatar." ON storage.objects;
DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;


-- =================================================================
-- Create new objects
-- =================================================================

-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  bio text,
  contact_number text
);
-- Set up Row Level Security (RLS)
alter table public.profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile for new users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for user addresses
create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  address_type text not null, -- 'billing' or 'shipping'
  title text,
  country text,
  city text,
  state text,
  zip text,
  street_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.addresses enable row level security;

create policy "Users can view their own addresses." on public.addresses
  for select using (auth.uid() = user_id);

create policy "Users can insert their own addresses." on public.addresses
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own addresses." on public.addresses
  for update using (auth.uid() = user_id);

create policy "Users can delete their own addresses." on public.addresses
  for delete using (auth.uid() = user_id);


-- Set up Storage!
-- Create a bucket for avatars if it doesn't exist
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Set up access policies for the avatars bucket.
create policy "Avatar images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Anyone can upload an avatar."
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );

create policy "Anyone can update their own avatar."
  on storage.objects for update
  using ( auth.uid() = owner )
  with check ( bucket_id = 'avatars' );
