-- Drop existing policies if they exist, to allow table modifications
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.categories;

-- Drop table if it exists to ensure a clean slate
DROP TABLE IF EXISTS public.categories;

-- Create the categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE
);

-- Enable Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policies for categories
CREATE POLICY "Enable all for authenticated users"
ON public.categories
FOR ALL
TO authenticated
USING (TRUE)
WITH CHECK (TRUE);

-- Add some seed data for demonstration
INSERT INTO public.categories (name, slug) VALUES
('Fruits & Vegetables', 'fruits-vegetables'),
('Meat & Fish', 'meat-fish'),
('Snacks', 'snacks');

-- Add sub-categories
INSERT INTO public.categories (name, slug, parent_id) VALUES
('Fruits', 'fruits', (SELECT id FROM categories WHERE slug = 'fruits-vegetables')),
('Vegetables', 'vegetables', (SELECT id FROM categories WHERE slug = 'fruits-vegetables')),
('Meat', 'meat', (SELECT id FROM categories WHERE slug = 'meat-fish')),
('Fish', 'fish', (SELECT id FROM categories WHERE slug = 'meat-fish')),
('Chips', 'chips', (SELECT id FROM categories WHERE slug = 'snacks')),
('Chocolate', 'chocolate', (SELECT id FROM categories WHERE slug = 'snacks'));
