
CREATE TABLE IF NOT EXISTS public.promos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    subtitle text,
    image_url text,
    button_text text,
    button_link text,
    status text NOT NULL DEFAULT 'inactive'::text,
    CONSTRAINT promos_pkey PRIMARY KEY (id)
);

ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to read promos" ON public.promos;
CREATE POLICY "Allow authenticated users to read promos" ON public.promos
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow admin users to manage promos" ON public.promos;
CREATE POLICY "Allow admin users to manage promos" ON public.promos
AS PERMISSIVE FOR ALL
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'super-admin', 'manager')
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'super-admin', 'manager')
);
