-- Create a table for public products
CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  name text,
  slug text UNIQUE,
  description text,
  unit text,
  price double precision DEFAULT 0,
  original_price double precision,
  stock integer DEFAULT 0,
  status text DEFAULT 'draft'::text,
  category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
  featured_image_url text,
  gallery_urls jsonb
);
COMMENT ON TABLE products IS 'Stores product information';

-- Create a join table for product tags (many-to-many)
CREATE TABLE IF NOT EXISTS product_tags (
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);
COMMENT ON TABLE product_tags IS 'Associates products with tags';


-- Set up Row Level Security (RLS)
-- PRODUCTS table
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to products" ON products;
CREATE POLICY "Allow all access to products" ON products FOR ALL
USING (true)
WITH CHECK (true);

-- PRODUCT_TAGS table
ALTER TABLE product_tags ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to product_tags" ON product_tags;
CREATE POLICY "Allow all access to product_tags" ON product_tags FOR ALL
USING (true)
WITH CHECK (true);


-- Create a bucket for product images if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('product_images', 'product_images', true)
ON CONFLICT (id) DO NOTHING;

-- Add RLS policies for the product_images bucket
-- Allow public read access to all images in the bucket
DROP POLICY IF EXISTS "Allow public read access to product images" ON storage.objects;
CREATE POLICY "Allow public read access to product images" ON storage.objects FOR SELECT
USING (bucket_id = 'product_images');

-- Allow authenticated users to upload, update, and delete their own images
DROP POLICY IF EXISTS "Allow insert for authenticated users on product images" ON storage.objects;
CREATE POLICY "Allow insert for authenticated users on product images" ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'product_images' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow update for authenticated users on product images" ON storage.objects;
CREATE POLICY "Allow update for authenticated users on product images" ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'product_images' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow delete for authenticated users on product images" ON storage.objects;
CREATE POLICY "Allow delete for authenticated users on product images" ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'product_images' AND auth.role() = 'authenticated');

-- Force schema reload for PostgREST
NOTIFY pgrst, 'reload schema';
